<!DOCTYPE html>
<html lang="en">
<head>
	<title>Digital Design and Development Agency | Plugg Resources</title>
	
	<!-- Meta Tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <meta name="msapplication-TileImage" content="assets/images/favicon.ico">
 
	<meta property="og:site_name" content="Digital Design and Development Agency | Plugg Resources">
	<meta property="og:title" content="Digital Design and Development Agency | Plugg Resources">
	<meta property="og:description" content="An online digital design and development agency specializing in the delivery of high quality tech solutions ranging from website and application development to corporate branding and general graphic design.">

	<meta property="og:image" itemprop="image" content="assets/images/favicon.ico">

	<meta property="og:type" content="website">
	<meta property="og:image:type" content="image/png">

	<meta property="og:image:width" content="300">
	<meta property="og:image:height" content="300">

	<meta property="og:url" content="https://pluggresources.com">


	<!-- Favicon -->
	<link rel="shortcut icon" href="assets/images/favicon.ico">

	<!-- Google Font -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Red+Hat+Display:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
	
	<!-- Plugins CSS -->
	<link rel="stylesheet" type="text/css" href="assets/vendor/font-awesome/css/all.min.css">
	<link rel="stylesheet" type="text/css" href="assets/vendor/bootstrap-icons/bootstrap-icons.css">
	<link rel="stylesheet" type="text/css" href="assets/vendor/tiny-slider/tiny-slider.css">
	<link rel="stylesheet" type="text/css" href="assets/vendor/glightbox/css/glightbox.min.css">

	
	<!-- Theme CSS -->
	<link rel="stylesheet" type="text/css" href="assets/css/style.css">
	<link rel="stylesheet" type="text/css" href="assets/css/custom.css">

  <!-- Animate on Scroll (AOS) -->
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

  <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />

    

    <!-- Demo styles -->
    <style>
      html,
      body {
        position: relative;
        height: 100%;
      }

      /* body {
        background: #eee;
        font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
        font-size: 14px;
        color: #000;
        margin: 0;
        padding: 0;
      } */

      .swiper {
        width: 100%;
        height: 100%;
      }

      .swiper-wrapper {
        /* width: 100%; */
      }

      .swiper-slide {
        /* text-align: center; */
        /* font-size: 18px; */
        /* background: rgba(var(--bs-primary-rgb), var(--bs-bg-opacity)) !important; */

        /* Center slide text vertically */
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
      }
      
      .swiper-slide img {
        display: block;
        width: 100%;
        height: 100%;
        object-fit: cover;
      }

      .swiper-button-next::after {
        font-size: 20px;
        font-weight: 900;
        color: #fff;
        padding-left: 180px;
      }

      .swiper-button-prev::after {
        font-size: 20px;
        font-weight: 900;
        color: #fff;
        padding-right: 180px;
      }

      .servCard:hover {
        background-color: #047467;
      }

      .servCard:hover h6 {
        color: #fff;
      }

      .servCard:hover p {
        color: #fff;
      }

      .servCard:hover a {
        color: #ffb900!important;
      }

      .servCard:hover .icon-md {
        background-color: #ffb900!important;
      }

      .servCard:hover .icon-md i {
        color: #fff!important;
      }
      
      .servCard:hover .icon-md {
        -webkit-animation: icon-mdHover 0.5s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
                animation: icon-mdHover 0.5s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
      }
      
      .servCard .icon-md {
        -webkit-animation: icon-md 0.5s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
                animation: icon-md 0.5s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
      }

      /* ----------------------------------------------
      * Generated by Animista on 2022-8-26 13:52:3
      * Licensed under FreeBSD License.
      * See http://animista.net/license for more info. 
      * w: http://animista.net, t: @cssanimista
      * ---------------------------------------------- */

      @-webkit-keyframes icon-mdHover {
        from {
          -webkit-transform: rotateY(0);
                  transform: rotateY(0);
        }
        to {
          -webkit-transform: rotateY(360deg);
                  transform: rotateY(360deg);
        }
      }
      @keyframes icon-mdHover {
        from {
          -webkit-transform: rotateY(0);
                  transform: rotateY(0);
        }
        to {
          -webkit-transform: rotateY(180deg);
                  transform: rotateY(180deg);
        }
      }


      @-webkit-keyframes icon-md {
        from {
          -webkit-transform: rotateY(180deg);
                  transform: rotateY(180deg);
        }
        to {
          -webkit-transform: rotateY(0);
                  transform: rotateY(0);
        }
      }
      @keyframes icon-md {
        from {
          -webkit-transform: rotateY(180deg);
                  transform: rotateY(180deg);
        }
        to {
          -webkit-transform: rotateY(0);
                  transform: rotateY(0);
        }
      }


      @media only screen and (min-width:992px) {
        .feat {
          margin-top: -120px;
        }
      }

    </style>

</head>

<body>

<!-- =======================
Header START -->
<header class="navbar-dark navbar-transparent">
	<!-- Logo Nav START -->
	<nav class="navbar navbar-expand-lg">
		<div class="container">
			<!-- Logo START -->
			<a class="navbar-brand" href="index.php">
				<img class="navbar-brand-item" src="assets/images/logo.svg" alt="logo">			
			</a>
			<!-- Logo END -->

			<!-- Responsive navbar toggler -->
			<button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">				
				<span class="navbar-toggler-icon"></span>
			</button>

			<!-- Main navbar START -->
			<div class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav navbar-nav-scroll mx-auto">
					<!-- Nav item 1 Home -->
					<li class="nav-item"><a class="nav-link" href="index.php">Home</a></li>

					<!-- Nav item 2 About -->
					<li class="nav-item"><a class="nav-link" href="about.php">About</a></li>

					<!-- Nav item 3 Portfolio -->
					<li class="nav-item"><a class="nav-link" href="portfolio.php">Portfolio</a></li>

					<!-- Nav item 4 Pricing -->
					<!-- <li class="nav-item"><a class="nav-link" href="pricing.php">Pricing</a></li> -->

          <!-- Nav item 5 Contact-->
					<li class="nav-item"><a class="nav-link" href="contact-us.php">Contact</a></li>
				</ul>
			</div>
			<!-- Main navbar END -->

			<!-- Nav right START -->
			<div class="blog-btn-div">
				<!-- Nav Button -->
				<a href="https://blog.pluggresources.com" class="blog-btn btn btn-dark mb-0 mx-2">Visit our Blog</a>
			</div>
			<!-- Nav right END -->

		</div>
	</nav>
	<!-- Logo Nav END -->
</header>
<!-- =======================
Header END -->

<!-- **************** MAIN CONTENT START **************** -->
<main style="z-index: 10;position: relative;">

<!-- =======================
Main banner START -->
<section class="position-relative main-seco">
	<div class="container pt-3" style="padding: 45px; margin-bottom: -30px;">
		<div class="row align-items-center mb-2">
          <div class="col-lg-12 z-index-9">
            <!-- Title -->
            <h1 class="text-white">Bringing your <span class="text-warning">digital ideas</span> to life!</h1>
            <!--Content -->
            <p class="text-white mb-0">We perfectly understand what modern businesses, products and brands need to succeed in the current world; an outstandingly developed visual identity and we're ready to help you build it!</p>

            <!-- Button -->
            <div class="my-4">
              <a href="about.php" class="btn btn-warning mb-0">Learn More</a>
              <!-- <a class="btn btn-white btn-white-shadow btn-round btn-lg ms-3 mb-0" data-glightbox="" data-gallery="hero"  href="https://www.youtube.com/embed/tXHviS-4ygo"><i class="fas fa-play"></i></a> -->
            </div>

              </div>
            </div><!-- RoW END -->
          </div>
        </div>
      </div>
</section>
<!-- =======================
Hero banner END -->

<!-- =======================
Service section START -->
<section class="services-section" data-aos="zoom-out-down">	
	<div class="container position-relative">

		<!-- Svg START-->
		<figure class="position-absolute top-0 end-0 mb-0 mt-n5 d-none d-lg-block">
			<svg class="fill-dark opacity-1" width="200" height="180">
				<path d="m128.8 75.204c-12-8.9-17.1-21.4-20.1-35-1.7-7.6-2.5-15.3-1.5-23.1 0.4-3.3 1-6.5 2.4-9.5 0.9-1.8 1.9-3.5 3.3-5 2.6-2.8 6.2-3.3 9.7-1.7 2.2 1 4 2.7 5.5 4.5 2.6 3.2 4.5 6.8 6 10.6 4 10 5.3 20.5 5.1 31.3-0.2 7.2-1 14.4-2.5 21.4-0.1 0.5-0.1 0.9-0.2 1.5 2.8 1.4 5.8 1.7 8.9 1.8 12.9 0.6 25.5-1.3 37.7-5.5 4-1.4 7.9-3 11.7-4.9 7.4-3.5 13.7-8.6 18.7-15 0.9-1.1 1.8-2.2 2.8-3.3 0.1-0.1 0.3-0.1 0.8-0.1-0.2 0.7-0.3 1.2-0.5 1.7-3.9 8.3-9.6 15-17.2 20.2-9.5 6.4-20 10.4-31.1 12.6-9.1 1.8-18.2 2.6-27.4 1.5-2-0.2-4.1-0.7-6.3-1.1-0.2 0.5-0.4 1.1-0.6 1.7-2.7 9.1-5.9 17.9-10.5 26.2-3.7 6.7-8 12.9-13.5 18.3-3 2.9-6.3 5.5-10 7.4-9.5 4.8-18.2 3.3-25.4-4.5l-1.4-1.4c-0.4 1.1-0.6999 1.9-1.1 2.8-2.5999 7.2-5.5 14.3-9.1999 21.1-3.2 5.8-6.9 11.3-11.7 16-2.3 2.3-4.8 4.2-7.7 5.7-7 3.5-13.7 3-20.1-1.6-1.2-0.8-2.2-1.8-3.5-2.8-0.4 1.1-0.7 1.9-1 2.8-2.7 8-5.9999 15.9-10.1 23.3-1 1.9-2.2 3.7-3.5 5.4-0.6 0.9-1.6 1.5-2.5 2.2-0.8 0.5-1.7 0.5-2.4-0.3s-0.4-1.6 0.2-2.4c1.2-1.7 2.3-3.5 3.3-5.3 5-9.1 8.8-18.7 11.9-28.5 0.2999-0.9 0.5-1.8-0.2-2.7-6.5-9.2-9.9-19.6-12-30.6-3-15.3-3.6-30.8-1.8-46.3 0.6-5.3 1.6-10.4 3.8-15.3 0.8-1.8 1.8-3.6 3-5.1 3-3.7 7.1-3.9 10.7-0.7 2.2 2 3.7 4.4 4.9001 7.1 2.5 5.2 3.8999 10.8 4.7999 16.5 1.8 10.9 1.8001 21.8 0.7001 32.8-1.3 13.4-3.9 26.6-7.5 39.5-0.4 1.5-0.4 2.6 0.8999 3.6 1.6001 1.3 3.1 2.8 4.8 3.9 3.8 2.4 7.8001 2.6 11.9 0.8 2.7999-1.2 5.1-3 7.2-5.1 3.7-3.5 6.5999-7.6 9.3-11.9 5.5999-9.2 9.7-19.1 13.1-29.3 0.3-0.9 0.4-1.6-0.1-2.5-4.5-9.1-6.5-18.9-7.5-28.9-1.1-10.8-1-21.6 0.7999-32.3 0.7001-4.1 1.6001-8.2 3.3001-12 0.6999-1.6 1.6-3.2 2.6999-4.5 2.7-3.2 6.5-3.1 9 0.2 1.2 1.6 2.1001 3.4 2.8001 5.3 1.9 5.3 2.5 10.9 2.9 16.5 1 17.9-2 35.4-7 52.5-0.2 0.6-0.3 1.2-0.6001 1.8-0.4 1-0.1999 1.9 0.4 2.7 1.4001 1.8 2.7001 3.8 4.4001 5.3 3.9 3.7 8.5999 4.6 13.6 2.6 2.6-1 5.1-2.6 7.4001-4.3 4-3 7.2-6.8 10.1-10.8 6.1-8.4 10.4-17.8 13.8-27.6 1.2-3.1 2.2-6.6 3.4-10.2zm-110.8 81.1c0.3-0.6 0.4-0.8 0.5-1.1 0.2001-0.5 0.3-1.1 0.5-1.6 3.7001-13.1 6.2001-26.5 7-40.1 0.6-9.9 0.4001-19.8-1.7999-29.6-1-4.4-2.1001-8.7-4.3001-12.7-1-1.7-2.2-3.3-3.6-4.7-1.3-1.3-2.7999-1.2-3.8999 0.4-1 1.4-1.9 3-2.5 4.6-2.2 5.5-3 11.3-3.5 17.2-1 12.9-0.3 25.7 1.9 38.5 1.6 9.1 3.9 18 8.1 26.3 0.5 0.7 0.9 1.6 1.6 2.8zm112.6-89.6c0.3-1.2 0.5-2 0.6-2.7 0.4-2.8 0.9-5.5 1.2-8.3 1.1-10.1 0.8-20.1-1.7-30-1.3-5.1-3.1-9.9-6-14.3-1.1-1.6-2.4-3-3.8-4.3-1.9-1.6-3.2-1.2-4.5 0.9-0.5 0.8-0.9 1.7-1.1 2.6-0.5 2.3-1.1 4.7-1.3 7.1-0.7 8.7 0.5 17.2 2.9 25.6 2.1 7.2 5.2 13.9 10.1 19.7 1 1.2 2.2 2.3 3.6 3.7zm-57.1-22.2c-0.2 0-0.5 0-0.7 0.1-0.5 0.9-1.2001 1.7-1.6001 2.6-0.6999 1.9-1.5 3.9-2 5.9-2.4 9.6-2.7999 19.4-2.2999 29.3 0.4 9 1.6 18 4.1999 26.7 0.2 0.7 0.5 1.4 0.8001 2.1 0.6-0.8 1-1.6 1.1-2.4 1.1999-5.9 2.6999-11.7 3.5999-17.6 1.8001-10.7 2.4001-21.5 1.1-32.2-0.4-3.6-1.3999-7.2-2.3999-10.7-0.2-1.4-1.1001-2.6-1.8-3.8z"/>
			</svg>
		</figure>
		<!-- Svg END -->

    


		<div class="row">
			<div class="col-lg-5 mb-3">
				<!-- Title -->
				<h2 class="mb-3">Our Services</h2>
				<!-- Content -->
				<p class="mb-0">From web applications, corporate websites all the way to visual branding and graphic design services, here's a snippet of our professional digital services, just for you!</p>
			</div>
		</div><!-- Row END -->

		<div class="row g-4">

			<div class="col-md-6 col-xl-3" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="300"> 
				<!-- Card START -->
				<div class="card card-body shadow rounded-4 rounded-bottom-right-0 p-4 servCard">					
					<!-- Icon -->						
					<div class="icon-md fs-6 text-primary bg-primary bg-opacity-25 rounded-3 rounded-bottom-right-0 mb-3">
						<i class="bi bi-laptop fa-fw"></i>
					</div>
					<!-- Title -->
					<h6 class="mb-3">Website Development</h6>
					<!-- Content -->
					<p class="card-text">Our skilled web designers and developers are constantly eager to deliver aesthetic, functional and responsive websites, whatever the kind, for your brand, business, school or company.</p>
					<!-- Button link -->
					<a href="about.php" class="card-link text-primary fw-bold">Learn more</a>
				</div> 
				<!-- Card END -->
			</div>

			<div class="col-md-6 col-xl-3" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="500"> 
				<!-- Card START  -->
				<div class="card card-body shadow  rounded-4 rounded-bottom-right-0 p-4 servCard">					
					<!-- Icon -->
					<div class="icon-md fs-6 text-primary bg-primary bg-opacity-25 rounded-3 rounded-bottom-right-0 mb-3">
					<i class="bi bi-menu-button-wide-fill fa-fw"></i>
					</div>					
					<!-- Title -->
					<h6 class="mb-3">Custom Software Development</h6>
					<!-- Content -->
					<p class="card-text">Need an online platform for specialized tasks and services? Not to worry! Send us a message to get personalized, standard web applications built for your company or service.</p>
					<!-- Button link -->
					<a href="about.php" class="card-link text-primary fw-bold">Learn more</a>            
				</div>				
				<!-- Card END -->
			</div>

			<div class="col-md-6 col-xl-3" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="700"> 
				<!-- Card START -->
				<div class="card card-body shadow rounded-4 rounded-bottom-right-0 p-4 servCard">
						<!-- Icon -->						
						<div class="icon-md fs-6 text-primary bg-primary bg-opacity-25 rounded-3 rounded-bottom-right-0 mb-3">
						<i class="bi bi-palette-fill fa-fw"></i>
						</div>
						<!-- Title -->
						<h6 class="mb-3">Graphic Design</h6>
						<!-- Content -->
						<p class="card-text">The success of every product, brand or company is largely determined by its visual branding. We offer eye-catching brand logos and designs of any sort for the growth of your business!</p>
						<!-- Button link -->
						<a href="about.php" class="card-link text-primary fw-bold">Learn more</a>            
					</div>
				<!-- Card END -->
			</div>

			<div class="col-md-6 col-xl-3" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="900"> 
				<!-- Card START  -->
				<div class="card card-body shadow rounded-4 rounded-bottom-right-0 p-4 servCard">				
					<!-- Icon -->
					<div class="icon-md fs-6 text-primary bg-primary bg-opacity-25 rounded-3 rounded-bottom-right-0 mb-3">
					<i class="bi bi-bezier fa-fw"></i>
					</div>
					<!-- Title -->
					<h6 class="mb-3">UI/UX Design</h6>
					<!-- Content -->
					<p class="card-text">Modern interfaces require just the right amount of research mixed with design to be deployed rightly to the satisfaction of clients and end-users. We are here to help you achieve this and many more!</p>
					<!-- Button link -->
					<a href="about.php" class="card-link text-primary fw-bold">Learn more</a>
				</div> 
				<!-- Card END -->
			</div>

		</div><!-- Row END -->
	</div>
</section>
<!-- =======================
Service section END -->

<!-- =======================
About section  END -->
<section class="bg-light position-relative py-5">

	<!-- Svg START-->
	<figure class="opacity-25 mb-0 position-absolute bottom-0 end-0 d-none d-lg-block">  
		<svg class="fill-dark" width="233" height="209">
			<path d="m42.126 51.038c-6.1 0-10.4-3.9-10.8-9.7-0.3-3.4 0.7-6.5 2.6-9.3 2-2.8 6.4-4.9 9.9-2.8 0.3 0.2 0.7 0.3 1.1 0.4 4.6 0.5 8.7 5.6 8.6 10.9-0.1 5.1-4.3 9.5-9.7 10.3-0.6 0.1-1.3 0.2-1.7 0.2z"/>
			<path d="m90.426 20.638c-6.9 0-11.4-5.6-9.8-12.4 0.5-2.3 1.6-4.4 3.3-6 1.9-1.8 4.1-2.7 6.8-2 1.2 0.3 2.4 0.3 3.5 0.6 4 0.8 6.8003 3.2 7.8003 7.2 1.1 4-0.4 7.2-3.4003 9.8-2.3 2-5.1 2.8-8.2 2.8z"/>
			<path d="m23.626 79.538c-0.1 6.7-6.4 11-12.5 8.4-8.4-3.5-9.2-12.6-5.5-18.4 0.9-1.4 2.2-2.3 3.8-2.8 1.4-0.4 2.9-0.5 3.9 0.4 1.6 1.5 3.6 2 5.3 3.1 3.1 2 5 5.5 5 9.3z"/>
			<path d="m37.626 182.54c-7.3 0-12.7-5.8-12.3-12.5 0.3-4.7 3.3-7 7.9-5.9 0.7 0.2 1.4 0.1 2.1 0.2 1.3 0.1 2.7 0.1 4 0.3 4.6 0.8 7.9 4.5 7.9 8.9 0 4.1-3.3 7.9-7.7 8.9-0.7 0-1.5 0-1.9 0.1z"/>
			<path d="m19.326 124.74c0 3.6-1.1 6.6-3.5 9-3.3 3.3-8.1 3.6-11.7 0.6-4.5-3.6-5.5-11.1-2.1-15.6 2.5-3.3 6.1-3.9 9.9-3.1 3.9 0.8 6.2 3.4 7.1 7.3 0.2 0.7 0.3 1.4 0.3 1.8z"/>
			<path d="m125.73 197.94c0-5.2 3.9-9 9.4-9 6.4 0 11 4.2 11 10.1 0 5.2-4.5 9.4-10 9.5-5.9 0-10.4-4.6-10.4-10.6z"/>
			<path d="m83.126 206.74c-6.3 0-12.4-6.1-12.3-12.4 0-4.4 3.4-6.8 7.6-5.5 1 0.3 2.2 0.3 3.3 0.3 4.6-0.2 8 1.9 9.5 5.8 2.3 5.9-1.7 11.9-8.1 11.8z"/>
			<path d="m202.63 178.74c0 4.4-3.7 8.3-8.3 8.8-4 0.4-8.2-2-9.7-5.7-1-2.4-0.9-4.7 0.6-6.8 0.1-0.2 0.3-0.4 0.4-0.6 3.4-4.7 8.5-5.6 13.4-2.4 2.3 1.6 3.6 4 3.6 6.7z"/>
			<path d="m124.73 13.538c0-2.1 0.5-3.8 1.6-5.4 2-3 5.2-3.8 8.4-2.1 1.3 0.7 2.5 1.4 3.7 2.3 2.6 2.1 3.7 4.8 2.9 8.1-0.8 3.4-3.1 5.5-6.6 6.2-3.3 0.6-6-0.6-8-3.2-1.4-1.8-2-3.8-2-5.9z"/>
			<path d="m222.83 126.14c5.3-0.1 9.4 4.3 9.3 9-0.1 2.8-1.1 5.1-3.2 7-4.4 4-11.1 1.9-12.4-3.9-0.3-1.3-0.4-2.8 0-4 0.6-2 1.6-4 2.6-5.9 1-1.6 2.7-2.2 3.7-2.2z"/>
			<path d="m146.03 79.538c0-0.3-0.1-0.7-0.1-1.1-0.2-3.3 1.6-5.5 4.7-6.2 4.3-0.9 9.1 2 10 6.1 1 4.3-1.8 8.5-6.2 9.6-4.5 1.1-9.4-2.3-8.6-7.4 0.1-0.3 0.1-0.6 0.2-1z"/>
			<path d="m65.926 61.838c0.1-3.1 0.9-5.5 2.9-7.3 3.4-3.1 8.1-2 9.6 1.7 0.4 0.9 0.9 1.7 1.4 2.5 1.4 2.7 1.5 5.4-0.3 7.9-1.7 2.4-4.1 3.5-7.1 3-3.2-0.5-5.1-2.5-6.1-5.4-0.2-1-0.3-1.9-0.4-2.4z"/>
			<path d="m104.23 149.94c2.7 1.2 6.2 2 8.1 5.3 1.5 2.7 0.9 6-1.4 8.4-2.4 2.4-5.9 3-8.8 1.6-4.2003-2.1-6.0003-7.9-3.7003-12 1.1-2.1 3.0003-3.3 5.8003-3.3z"/>
			<path d="m147.63 158.34c-4.3 0-7.8-3.6-7.6-7.9 0.1-1.7 0.6-3.5 1.4-5 1.2-2.4 3.5-3.3 6-2.8 1.7 0.3 3.4 1 4.8 2 3 2 4.1 5.3 3.1 8.3-1 3.2-4.3 5.4-7.7 5.4z"/>
			<path d="m48.226 92.838c0-2.2 0.6-4.1 2.2-5.6 2.5-2.3 6.1-2.1 8.2 0.5 0.7 0.9 1.4 1.7 2.2 2.5 1.2 1.2 2.1 2.6 2.5 4.3 1 4.7-2.9 8.7004-7.6 7.8004-4.1-0.7-7.4-4.9004-7.5-9.5004z"/>
			<path d="m174.53 41.738c-2.9 0-5.4-1.8-6.1-4.7-0.3-1.3-0.8-2.5-1.7-3.6-2.1-2.5-1.3-6 1.6-7.5 0.6-0.3 1.3-0.6 2-0.7 4.7-0.6 10.3 3.7 10.8 8.4 0.5 4.3-2.6 8.1-6.6 8.1z"/>
			<path d="m107.63 50.838c0 2.4-0.4 4.2-1.6 5.9-2.5 3.6-7.4003 3.9-10.3 0.5-2.4-2.7-2.6-6.5-0.7-9.5 0.4-0.7 0.8-1.4 1.1-2.1 1.6-4 6.1003-4.9 9.0003-1.7 2 2.1 2.5 4.6 2.5 6.9z"/>
			<path d="m205.43 62.638c0 3.8-2.8 6.8-6.5 7.1-4 0.3-7.5-2.6-7.9-6.7-0.2-1.5-0.1-3 0-4.5 0.3-2.6 2.4-4.4 5.1-4.6 4.5-0.4 9.4 4.2 9.3 8.7z"/>
			<path d="m226.63 92.038c0 3.8-3 7.2-6.9 7.6-3.6 0.4004-7.1-2-7.8-5.6-0.5-2.4 0.1-4.8 1.1-6.9 0.4-0.9 1.5-1.7 2.4-2.2 4.7-2.3 11.2 1.8 11.2 7.1z"/>
			<path d="m180.03 117.24c0 3.3-2.1 6.1-5.3 6.8-3 0.7-6-0.9-7.4-3.9-0.4-0.8-0.9-1.7-1.5-2.4-2.1-2.9-1.1-6.7 2.2-8.2 5.2-2.3 12 2.1 12 7.7z"/>
			<path d="m131.73 58.138c0 0.3 0 0.7-0.1 1.2-0.5 3.4-2.9 5.8-6 5.8-3 0-5.5-2.2-6.1-5.4-0.3-1.8-0.7-3.6-1-5.4-0.4-2.1 0.1-4 1.9-5.3 1.9-1.4 3.9-1.3 5.9-0.2 2.7 1.4 5.4 5.9 5.4 9.3z"/>
			<path d="m77.626 136.04c-0.2 2.6-1.5 4.8-4.2 6s-5.3 0.8-7.6-1.2c-2.7-2.3-3.6-6.6-2.1-9.9s5.2-4.6 8.5-2.9c3.4 1.7 5.4 4.6 5.4 8z"/>
			<path d="m101.03 93.738c-0.1 1.5-0.1 2.5-0.2 3.4-0.4 2.4-1.8003 4.0004-4.2003 4.7004-2.3 0.6-4.3-0.1-5.8-1.8-2.8-3.0004-2.5-8.2004 0.3-11 1.9-1.8 4.6-2.3 6.9-1.2 2.2003 1 3.2003 3.1 3.1003 5.7-0.1 0.3-0.1 0.5-0.1 0.2z"/>
			<path d="m126.23 130.24c0 2.6-1.9 4.8-4.6 5.4-2.6 0.6-4.9-0.1-6.8-2.1-1.8-2-2.4-4.3-1.7-6.9 0.6-2.2 2.1-3.6 4.3-4.1 2.1-0.5 3.9 0.2 5.4 1.8 0.6 0.7 1.3 1.4 1.9 2.1 1.1 1.1 1.6 2.3 1.5 3.8z"/>
			<path d="m100.73 119.84c-0.1 3.2-1.1003 5.1-3.3003 6.2s-4.4 0.8-6.3-0.7c-2.9-2.2-3.6-6.7-1.7-9.8 2.3-3.7 7.3-3.7 9.5 0.1 0.9 1.4 1.4003 3.2 1.8003 4.2z"/>
			<path d="m137.03 101.04c0 3-1.7 5.5-4.3 6.2s-5.4-0.5-6.8-3.1c-0.9-1.6-1.3-3.4-0.9-5.3004 0.5-2.4 1.9-4 4.3-4.6 2.3-0.6 4.2 0.2 5.8 1.9 1.3 1.3 1.8 3.1 1.9 4.9004z"/>
			<path d="m121.53 89.338c-3.3 0-6.3-3.1-6.3-6.5 0-3 2.3-5.3 5.3-5.2 3.9 0 6.9 2.6 6.9 5.8 0 3.1-2.7 5.9-5.9 5.9z"/>
		</svg>
	</figure>
	<!-- SVG END -->

	<div class="container">
		<div class="row align-items-center g-4 g-xl-5">

			<div class="col-lg-6 position-relative">

				<!-- Svg START -->
				<figure class="position-absolute top-0 start-0 mt-3 mb-0 z-index-9 d-none d-lg-block">          
					<svg class="fill-warning">         
						<path d="M35.2,1.6c37.3,18.9,72.2,41.8,107.4,64.1c-0.2,0.4-0.4,0.8-0.6,1.2c-1.9-0.8-3.9-1.5-5.6-2.5c-30.3-17-60.6-34.1-91-51.1c-4.1-2.3-8.1-4.6-12.2-6.9c-2.3-1.2-2.8-2.7-1-4.7C33.2,1.6,34.2,1.6,35.2,1.6z"/>
						<path d="M154,164.4c-5-3.8-10-7.6-15-11.3c-42.7-31.3-86.7-60.7-133-86.5c-1.8-1-3-3.3-4.4-4.9c2.3,0.2,5-0.4,6.9,0.6
						c12.9,7.3,25.8,14.5,38.3,22.4c36.4,22.8,71.8,47.2,104.1,75.7c1.2,1.1,2.5,2.2,3.7,3.3C154.3,163.8,154.1,164.1,154,164.4z"/>
						<path d="M137.4,81.7C93.8,56.6,50.2,31.6,6.6,6.5C6.1,6.2,6.1,5.1,5.2,2.5c4.4,1.6,7.6,2.4,10.5,3.9c10,5.3,20,10.6,29.7,16.5
						c29.9,18.5,59.6,37.2,89.4,55.9c1.1,0.7,2.1,1.5,3.1,2.2C137.7,81.2,137.6,81.5,137.4,81.7z"/>
						<path d="M122.8,88.8C87.6,68.9,52.4,49,17.2,29c-0.6-0.4-0.8-1.6-1.9-4c3.7,1.1,6.3,1.3,8.3,2.5c20.1,11.4,40.3,22.7,60.1,34.5 c12.1,7.2,23.8,15.3,35.6,23.1c1.4,0.9,2.6,1.9,3.9,2.9C123.1,88.3,122.9,88.6,122.8,88.8z"/>
						<path d="M111.3,103.9c-1.8-1-3.7-1.9-5.5-2.9c-27-15.4-54.1-30.8-81-46.3c-2.1-1.2-5.3-5.2-5.1-5.4c2.8-3.3,5.4-0.2,7.6,1.2
						c27.6,17,55.2,34.1,82.7,51.3c0.6,0.4,1.2,0.9,1.7,1.4C111.6,103.3,111.5,103.6,111.3,103.9z"/>       
					</svg>              
				</figure>
				<!-- Svg END -->

				<div class="row">
					<div class="col-lg-8 position-relative">
						<!-- Message Box -->
						<div class="col-9 position-absolute top-0 end-0 translate-middle-y mt-9 me-n9 d-none d-lg-block z-index-9">
							<div class="bg-white rounded-3 shadow position-relative py-3 px-4">
								<div>
									<!-- Icon -->
									<i class="bi bi-check2-circle text-primary fs-4"></i>
								</div>
								<!-- Title -->
								<h6>Creative insight</h6>
								<!-- Content -->
								<p class="mt-2 mb-0 text-dark">With creativity at the very centre of our values, every project is greatly unique!</p>
							</div>
						</div>

						<div class="position-relative">
							<!-- Svg  START-->
							<figure class="position-absolute bottom-0 start-0 z-index-9 mb-0">
								<svg class="fill-light" width="47px" height="70.5px" viewBox="0 0 47 70.5"
									style="enable-background:new 0 0 47 70.5;" xml:space="preserve">
									<rect class="st0" width="23.5" height="23.5" />
									<rect x="23.5" y="23.5" class="st0" width="23.5" height="23.5" />
									<rect y="47" class="st0" width="23.5" height="23.5" />
								</svg>
							</figure>
							<!-- Svg  END-->
							<!-- Image -->
							<div class="hero-guy-5 rounded-top-left-10">
							<!-- <img src="assets/images/about/01.jpg" class="rounded-top-left-10" alt="about"> -->
							</div>
						</div>

						<!-- Avatars -->
						<div class="my-4">
							<ul class="avatar-group align-items-center">
								<li class="avatar">
									<!-- Image -->
									<img class="avatar-img rounded-circle" src="assets/images/avatar/Eloka.jpeg" alt="avatar">
								</li>
								<li class="avatar">
									<!-- Image -->
									<img class="avatar-img rounded-circle" src="assets/images/avatar/paschal.jpg" alt="avatar">
								</li>
								<li class="avatar">
									<!-- Image -->
									<img class="avatar-img rounded-circle" src="assets/images/avatar/AdobeStock_443352225.jpeg" alt="avatar">
								</li>
								<li class="list-unstyled ms-4">100% Customer satisfaction</li>
							</ul>
						</div>	
					</div>
					<div class="col-lg-4 mt-auto position-relative">
						
						<!-- Svg START-->
						<figure class="position-absolute top-50 end-0 me-6 mt-4 rotate-50 mb-0 d-none d-xl-block">          
							<svg class="fill-primary">
								<path d="m145.18 2.3094c0.013 0.05057 0.025 0.10115 0.039 0.15123h7.785c-4e-3 -0.05008-7e-3 -0.10066-0.011-0.15123h-7.813zm-75.923 60.654c2.6132-2.573 5.4727-4.9518 6.8582-8.4913-2.2859 2.8309-4.5718 5.6608-6.8582 8.4913zm13.4-29.32c0-0.5048 0.041-1.0136-0.0061-1.5138-0.7577-8.0639-7.3619-10.147-13.26-8.504-1.9232 0.5351-3.5434 1.5796-5.0923 2.7187-1.3804 1.0146-2.7538 2.1375-3.8206 3.4621-2.6622 3.3069-4.1807 7.2026-4.9956 11.332-1.1336 5.7448-1.3638 11.489 0.8118 17.087 1.2742 3.2765 3.1489 6.0898 6.2385 7.9824 0.8888 0.5443 1.4609 0.3885 2.1473-0.2721 5.0382-4.8475 9.6716-10.022 13.099-16.17 2.7978-5.0175 4.8282-10.274 4.8783-16.122zm46.11-28.008c4.129-0.95444 8.257-1.9084 12.386-2.8628-3.236 0.47899-6.455 1.0945-9.651 1.8128-0.937 0.21042-1.808 0.71267-2.712 1.0778-1.922-0.03793-3.379 1.0799-4.884 2.0717 1.62-0.69951 3.241-1.3995 4.861-2.0996zm-67.444 63.257c-5.0923-3.2017-8.2487-7.6709-9.7086-13.168-2.7907-10.51-1.1781-20.354 5.5319-29.044 3.1508-4.0812 7.4854-6.633 12.648-7.3942 4.3589-0.6424 8.1703 0.8108 11.393 3.754 3.206 2.927 5.2744 6.5789 5.6214 10.888 0.2969 3.6928-0.0303 7.4433-1.4467 10.954-1.1336 2.8087-2.298 5.6169-3.6845 8.3047-0.8351 1.619-2.0739 3.0438-3.2141 4.4904-2.6799 3.3984-5.4094 6.7574-8.0772 10.425 0.999-0.2858 2.0405-0.4725 2.989-0.8771 3.0608-1.3065 5.5101-3.4642 7.6988-5.9052 5.2729-5.8813 8.793-12.839 12.119-19.915 2.8924-6.1545 5.8359-12.285 9.7974-17.856 7.759-10.912 18.13-17.866 31.228-20.789 8.022-1.79 16.142-1.485 24.264-1.4521 3.056 0.01213 6.115-0.23571 9.172-0.35912 0.167-0.007081 0.337 0.042992 0.693 0.092559-0.37 0.34698-0.618 0.57964-0.668 0.62618 0.435 0.35355 0.877 0.71367 1.319 1.0733-0.379 0.45117-0.674 1.0703-1.158 1.3136-0.718 0.36063-1.559 0.568-2.365 0.64084-2.215 0.19979-4.44 0.27414-6.659 0.43751-2.533 0.18715-5.062 0.43145-7.596 0.61606-0.615 0.04502-1.248-0.11886-1.86-0.05918-2.929 0.28527-5.876 0.48456-8.774 0.96658-2.602 0.43347-5.129 1.3156-7.729 1.7723-1.981 0.34798-3.8 1.046-5.611 1.835-4.356 1.8993-8.508 4.0469-12.102 7.3093-5.042 4.5754-9.055 9.9399-12.55 15.674-2.082 3.4171-3.4219 7.2799-5.2212 10.88-1.8584 3.7171-3.8393 7.3745-5.8247 11.026-1.0005 1.8401-1.9687 3.7348-3.2409 5.3811-1.6232 2.1016-3.4852 4.0292-5.3477 5.9305-1.209 1.2326-2.4908 2.4597-3.9359 3.3812-3.3537 2.1406-7.0489 2.79-10.925 1.7111-1.1827-0.3287-2.0264-0.219-2.9845 0.6212-7.0888 6.2167-14.997 11.188-23.598 15.015-5.1318 2.2837-10.28 4.5936-15.589 6.3958-6.8481 2.3241-13.95 3.62-21.246 3.316-1.1796-0.0491-2.3769-0.2782-3.508-0.6186-0.47043-0.1416-0.78809-0.7926-1.1751-1.2114 0.4244-0.2837 0.82502-0.7516 1.2788-0.8103 0.77393-0.1001 1.5823 0.0471 2.3739 0.1093 0.53517 0.042 1.0744 0.2053 1.599 0.1623 5.6578-0.4673 11.181-1.6569 16.556-3.4368 14.002-4.6377 26.83-11.442 38.143-20.981 0.4163-0.3511 0.8139-0.7254 1.3739-1.2261z"/>
							</svg>
						</figure> 
						<!-- Svg END -->

						<!-- Image -->
						<div class="hero-guy-6 rounded-3">
						<!-- <img src="assets/images/about/02.jpg" class="rounded-3" alt="about"> -->
						</div>
					</div>  
				</div><!-- Row END -->				
			</div>
			
			<div class="col-lg-6">
				<!-- Title -->
				<h2 class="mb-3">The perfect blend of Design & Dev</h2>
				<!-- Content -->
				<p class="mb-0">Getting the right balance between eye-catching visuals and functionality is always vital in the grand scale of digital technology. At Plugg Resources, we understand just how important this is for the successful promotion and consumption of products and therefore, continue to strive towards perfection.</p>
				<!-- Counter START -->
				<div class="row g-4 desdev">
					<!-- First counter column -->
					<div class="col-sm-4 col-md-6 col-xl-4">
						<div class="d-flex">
							<h3 class="purecounter text-primary" data-purecounter-start="0" data-purecounter-end="30" data-purecounter-delay="100">30</h3>
							<span class="text-primary display-6">+</span>
						</div>
						<!-- Title -->
						<h6 class="mb-0">Completed projects</h6>
					</div>

					<!-- Second counter column -->
					<div class="col-sm-4 col-md-6 col-xl-4">
						<div class="d-flex">
							<h3 class="purecounter text-primary" data-purecounter-start="0" data-purecounter-end="100" data-purecounter-delay="100">100</h3>
							<span class="text-primary display-6">+</span>
						</div>
						<!-- Title -->
						<h6 class="mb-0">Happy Clients</h6>
					</div>
					
					<!-- Third counter column -->
					<div class="col-sm-4 col-md-6 col-xl-4">
						<div class="d-flex">
							<h3 class="purecounter text-primary" data-purecounter-start="0" data-purecounter-end="30" data-purecounter-delay="100">30</h3>
							<span class="text-primary display-6">+</span>
						</div>
						<!-- Title -->
						<h6 class="mb-0">Referrals & Recommendations</h6>
					</div> 
				</div>
				<!-- Counter END -->	

				<!-- Button -->
				<a class="btn btn-warning mt-4" href="portfolio.php">Learn More</a>
			</div>

		</div><!-- Row END -->
	</div>	
</section>
<!-- =======================
About section  START -->

<!-- =======================
Testimonial section  START -->
<section data-aos="zoom-out-down">
	<div class="container">

		<div class="row">
			<div class="col-lg-5 text-center mx-auto">
				<!-- Title -->
				<h2 class="mb-3">What our clients say</h2>
				<!-- Content -->
				<p>Get to know what businesses and individuals think of us</p>
			</div>
		</div><!-- Row END -->    

		<div class="row">

			<div class="col-12">
				<!-- Tiny Slider START -->
				<div class="tiny-slider arrow-round arrow-gray arrow-hover">
					<div class="tiny-slider-inner my-3" data-autoplay="true" data-edge="20" data-arrow="true" data-dots="false" data-items-xl="3" data-items-md="2" data-items-sm="1">

						<div>
							<!-- Card START -->	
							<div class="card card-body card-bg-scale-border rounded-4 rounded-bottom-right-0 px-3 py-4">
								<!-- Card header START -->
								<div class="card-header pb-0">
									<div class="d-flex align-items-center">
										<div class="avatar avatar-lg flex-shrink-0">
											<!-- Avatar -->
											<img class="avatar-img rounded-circle" src="assets/images/avatar/Eloka.jpeg" alt="avatar">
										</div>
										<div class="ms-3 flex-shrink-1">
											<!-- Card title -->
											<h6 class="mb-1">Eloka Anthony</h6>
											<!-- Card sub-title -->
											<span class="mb-2 fw-bold small">Awka, Nigeria</span>								
										</div>		
									</div>
								</div>
								<!-- Card header END -->
								<!-- Card Body START -->
								<div class="card-body pt-0">
									<!-- Ratting -->
									<ul class="list-inline my-2">
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>									
									</ul>
									<!-- Content -->
									<p class="card-text">You guys are really good at this, the whole site is fast and responsive. I really appreciate.</p>
								</div>
								<!-- Card body END -->
							</div>
							<!--Card END  -->
						</div>

						<div>
							<!-- Card START -->	
							<div class="card card-body card-bg-scale-border rounded-4 rounded-bottom-right-0 px-3 py-4">
								<!-- Card header START -->
								<div class="card-header pb-0">
									<div class="d-flex align-items-center">
										<div class="avatar avatar-lg flex-shrink-0">
											<!-- Avatar -->
											<img class="avatar-img rounded-circle" src="assets/images/avatar/403022_business man_male_user_avatar_profile_icon (1).png" alt="avatar">
										</div>
										<div class="ms-3 flex-shrink-1">
											<!-- Card title -->
											<h6 class="mb-1">Melvin | CEO, Bube.app</h6>
											<!-- Card sub-title -->
											<span class="mb-2 fw-bold small">Enugu, Nigeria</span>								
										</div>		
									</div>
								</div>
								<!-- Card header END -->
								<!-- Card Body START -->
								<div class="card-body pt-0">
									<!-- Ratting -->
									<ul class="list-inline my-2">
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-half text-warning"></i></li>									
									</ul>
									<!-- Content -->
									<p class="card-text">I am highly impressed with the scintillating and astonishing service of this company, the logos were elegantly designed and curated, the flyers have been amazing.</p>
								</div>
								<!-- Card body END -->
							</div>
							<!--Card END  -->
						</div>

						<div>
							<!-- Card START -->	
							<div class="card card-body card-bg-scale-border rounded-4 rounded-bottom-right-0 px-3 py-4">
								<!-- Card header START -->
								<div class="card-header pb-0">
									<div class="d-flex align-items-center">
										<div class="avatar avatar-lg flex-shrink-0">
											<!-- Avatar -->
											<img class="avatar-img rounded-circle" src="assets/images/avatar/AdobeStock_443352225.jpeg" alt="avatar">
										</div>
										<div class="ms-3 flex-shrink-1">
											<!-- Card title -->
											<h6 class="mb-1">Ada Christabel</h6>
											<!-- Card sub-title -->
											<span class="mb-2 fw-bold small">Asaba, Nigeria</span>								
										</div>		
									</div>
								</div>
								<!-- Card header END -->
								<!-- Card Body START -->
								<div class="card-body pt-0">
									<!-- Ratting -->
									<ul class="list-inline my-2">
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>									
									</ul>
									<!-- Content -->
									<p class="card-text">Plugg Resources are the best in the design world. I so much love the flyers and Christmas card you guys designed for me. More grace.</p>
								</div>
								<!-- Card body END -->
							</div>
							<!--Card END  -->
						</div>

						<div>
							<!-- Card START -->	
							<div class="card card-body card-bg-scale-border rounded-4 rounded-bottom-right-0 px-3 py-4">
								<!-- Card header START -->
								<div class="card-header pb-0">
									<div class="d-flex align-items-center">
										<div class="avatar avatar-lg flex-shrink-0">
											<!-- Avatar -->
											<img class="avatar-img rounded-circle" src="assets/images/avatar/paschal.jpg" alt="avatar">
										</div>
										<div class="ms-3 flex-shrink-1">
											<!-- Card title -->
											<h6 class="mb-1">Ezioha Paschal</h6>
											<!-- Card sub-title -->
											<span class="mb-2 fw-bold small">Onitsha, Nigeria</span>								
										</div>		
									</div>
								</div>
								<!-- Card header END -->
								<!-- Card Body START -->
								<div class="card-body pt-0">
									<!-- Ratting -->
									<ul class="list-inline my-2">
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>
										<li class="list-inline-item me-0"><i class="bi bi-star-fill text-warning"></i></li>									
									</ul>
									<!-- Content -->
									<p class="card-text">Amazing web design service. The best I have seen so far.</p>
								</div>
								<!-- Card body END -->
							</div>
							<!--Card END  -->
						</div> 

					</div>	
				</div>
				<!-- Tiny Slider END -->
			</div>	

		</div><!-- Row END --> 

	</div>
</section>
<!-- =======================
Testimonial section START -->


<!-- =======================
Action box START -->
		<div class="row">
			<div class="col-12">        
				<div class="bg-dark rounded-3 py-5 position-relative overflow-hidden">

					<!-- Svg START -->
					<figure class="position-absolute top-100 start-100 translate-middle">        
						<svg class="fill-warning" width="288.8px" height="272px" viewBox="0 0 288.8 272" style="enable-background:new 0 0 288.8 272;" xml:space="preserve">
							<path d="M168,270.2c-6.3,0-12.5,0-18.8,0c-0.7-0.2-1.4-0.6-2.1-0.7c-24.1-2.2-47.2-8.7-70-16.6C37.9,239.3,13.4,212.4,4,171.9 c-1.8-7.6-2.7-15.5-4-23.2c0-5.1,0-10.1,0-15.2c1.1-5.1,1.2-10.5,3.3-15.1C16.9,88.7,33.6,61,57.7,38.5C90.3,8.1,128.9-4.7,173,1.5 c53.8,7.6,96.8,47.7,109.3,100.8c2.1,9.1,3.1,18.4,4.6,27.6c0,5.4,0,10.7,0,16.1c-0.9,6.3-1.7,12.6-2.7,18.9
							c-8.6,50.8-46.3,90.6-96.5,101.9C181.2,268.3,174.6,269.1,168,270.2z"/>
						</svg>
					 </figure>
					<!-- Svg END -->

					<!--Svg START  -->
					<figure class="position-absolute top-0 start-0 mt-n5 ms-n6">
						<svg class="fill-primary">
							<path d="M246.5,14.2c0,2.4,0,4.9,0,7.3c-0.6,1.9-1.3,3.7-1.8,5.6c-3.6,12.2-9.3,23.1-19.6,31.2c-2.6,2.1-5.3,4.1-8,6.2
							C194,82.1,167.9,95,142.3,108.5c-19.9,10.5-40,20.9-60.4,30.6c-12.6,6-26.3,8.1-40.2,5.2c-11.5-2.3-21.7-7-26.6-18.6
							C9.8,113.1,5,100.3,0,87.5c0-3.4,0-6.7,0-10.1c1.2-4,2.8-8,3.7-12.1C9.3,39.1,35.5,21,62.8,29.8c19.5,6.3,39.4,7.3,59.6,3.1
							c14.9-3.1,28-10.4,41.2-17.1c15.5-7.9,31.9-13,49.1-15.1C226.3-0.9,239.6-1.2,246.5,14.2z"/>
							<path d="M121.1,29.2"/>
							<path d="M256.6,8.8"/>
						</svg> 
					</figure>
					<!-- Svg END -->
			 
					<div class="row">
						<div class="col-10 mx-auto">
							<div class="row align-items-center py-4">
								<div class="col-lg-4 position-relative">
									<!-- Title -->
									<h2 class="text-white z-index-9 mb-0">What we are known for!</h2>
									
									<!--Svg START  -->
									<figure class="position-absolute top-50 end-0 mt-n5 mb-0 me-n9 rotate-330 d-xxl-block d-none">
										<svg class="fill-primary opacity-2" width="288.8" height="100">
											<path d="M0.9,85.1c6.3,1,12.6,2.7,19,3c28.3,1.3,55.2-4.6,80.8-16.6c0.5-0.2,1-0.6,1.9-1.3C92.8,60,91.9,47.8,94.4,35c2.3-11.6,8.2-21.3,17.8-28.1c4.2-3,9.5-5.6,14.6-6.5c17.3-3.1,31.2,12.1,27.5,29.2c-2.6,12.2-10.1,21.2-19.1,29
											c-5.5,4.8-11.6,8.9-17.4,13.3c0.2,0.5,0.5,1.1,0.7,1.6c4.4-1.5,9.3-2.2,13.1-4.7c6.8-4.5,13.4-9.7,19.2-15.4
											c7.2-7.1,13.4-15.2,20.2-22.8c18-20.2,40.1-31.9,67.8-30c9.4,0.6,18.7,3,27.9,4.9c5.9,1.2,11.7,2.7,17.5,4.4
											c2.1,0.6,3.9,2.2,5.8,3.3c-0.1,0.3-0.1,0.6-0.2,0.9c-2.4,0.3-4.9,1.3-7.3,0.9c-13.1-2-26-4.8-39.2-6.3c-29.5-3.3-52,9.5-70.5,31.2 c-6.6,7.7-13,15.7-20.4,22.7c-6.1,5.8-13.4,10.5-20.6,14.9c-5.7,3.5-12.2,3.4-18.2,0.4c-3.5-1.7-6.1-1.1-9.3,0.3 c-25.3,11.5-52.1,16-79.8,15.4c-2.4-0.1-4.8-0.3-7.2-0.4c-5.8-1.5-11.7-3-17.5-4.5C0.3,87.5,0.6,86.3,0.9,85.1z M144.1,26.6 c1.3-12.3-7.7-20.1-19.8-17c-8.2,2.1-14.5,7.2-18.6,14.5c-4.9,8.7-7,18.1-6.5,28c0.3,7.6,2.6,14.7,8.5,20.1c2,1.9,3.9,2.7,6.1,0.3 c7.2-7.8,14.8-15.2,21.5-23.3C140.4,42.8,143.2,34.9,144.1,26.6z"/>
										</svg>
									</figure>
									<!-- Svg END  -->

								</div>
								<div class="col-lg-8">
									<!-- Content -->
									<p class="text-white">At Plugg Resources, we let our creativity speak for us. With professionally qualified designers and developers to attend to your requests, be sure to expect the best visual appeal has to offer.</p>
									<!-- Button -->
									<a class="btn btn-primary mb-0" href="index.php #get-started">Get Started</a>
								</div>
							</div><!-- Row END -->
						</div>
					</div><!-- Row END -->    
				</div>
			</div>
		</div><!-- Row END -->

	</div>
</section>
<!-- =======================
Action box END -->

<!-- =======================
Step START -->
<section style="margin-top: -50px;">
	<div class="container">
		<!-- Tabs -->
		<div class="row align-items-center g-4">

			<div class="col-lg-6"> 
				<!-- Tabs START -->
				<div class="nav flex-column nav-pill nav-pill-border-left me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="500">
					<!-- Tab item START -->
					<a class="nav-link mb-3 active " id="step-1" data-bs-toggle="pill" data-bs-target="#step1"  role="tab" aria-controls="step1" aria-selected="true">
					<div class="d-flex">
						<!-- Step -->
						<h2 class="text-primary opacity-3 mb-0">01</h2>
						<div class="ms-3">
							<!-- Title -->
							<h5>Warm & quick responses</h5>
							<!-- Content -->
							<p class="mb-0">Our friendly designers and developers are available to attend to your requests and enquiries on all work days!</p>
						</div>
					</div>
					</a>
					<!-- Tab item END-->

					<!-- Tab item START-->
					<a class="nav-link mb-3" id="step-2" data-bs-toggle="pill" data-bs-target="#step2" role="tab" aria-controls="step2" aria-selected="false" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="700">
						<div class="d-flex">            
								<!-- Step -->
								<h2 class="mb-2 text-primary opacity-3 mb-0">02</h2>              
							<div class="ms-3 align-items-start">
								<!-- Title -->
								<h5>Professionally skilled personnel</h5>
								<!-- Content -->
								<p class="mb-0">With expert web designers, software developers and graphic designers, be sure to sit back and be guaranteed pure excellence.</p>
							</div>
						</div>
					</a>
					<!-- Tab item END -->
					
					<!-- Tab item START -->
					<a class="nav-link" id="step-3" data-bs-toggle="pill" data-bs-target="#step3" role="tab" aria-controls="step3" aria-selected="false" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="900">
						<div class="d-flex">
							<!-- Step -->
							<h2 class="mb-2 text-primary opacity-3">03</h2>
							<div class="ms-3 align-items-start mb-0">
								<!-- Title -->
								<h5>Safe & secure interactions</h5>
								<!-- Content -->
								<p class="mb-0">As a registered company under the FGN, your conversations and transactions are safe with us! Also, all payments for services will be issued receipts accordingly.</p>
							</div>
						</div>
					</a>
					<!--Tab item END  -->
				</div>
				<!-- Tabs END -->
			</div>

			<div class="col-lg-6 position-relative" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="500">

				<!-- Svg START -->
				<figure class="position-absolute top-0 end-0 me-n3 mt-n3 z-index-9 d-none d-lg-block">
				<svg class="fill-primary" width="120" height="105" viewBox="0 0 120 105"  xmlns="http://www.w3.org/2000/svg">
					<path fill-rule="evenodd" clip-rule="evenodd" d="M107.952 83.3619C107.182 83.9654 106.82 84.8398 106.665 85.8227C106.58 86.3649 106.085 86.439 105.713 86.5343C105.39 86.6171 105.093 86.6279 104.832 86.8938C104.725 87.004 104.388 87.028 104.247 86.9418C103.795 86.6664 103.311 86.4651 102.894 86.0977C101.426 84.8054 100.349 83.207 99.3413 81.5763C98.3132 79.9124 97.2371 78.2664 96.4497 76.4617C96.2049 75.9001 96.195 75.9046 96.8113 75.4685C97.3125 76.4215 97.7797 77.3891 98.3207 78.3136C98.7498 79.0472 99.2688 79.7273 99.7915 80.4948C99.9145 80.1858 99.9116 79.9878 99.7207 79.7124C98.681 78.2105 97.694 76.6746 96.9112 74.9159C97.0362 74.8343 97.1874 74.7353 97.3378 74.6376C97.3726 74.6674 97.45 74.7345 97.5826 74.8492V74.223C97.9541 74.1488 98.2909 74.0821 98.7291 73.9951C99.0708 74.1546 99.2332 74.7593 99.7957 74.8343C99.7774 75.4461 100.312 75.7509 100.581 76.1979C100.914 76.7521 101.366 77.2346 101.686 77.6443C102.047 77.5962 102.317 77.5457 102.59 77.5266C103.547 77.4595 103.523 77.4898 104.119 78.0154C104.782 78.5994 105.235 79.4166 106.089 79.7878C106.144 79.8114 106.205 79.895 106.208 79.9534C106.235 80.5681 106.579 80.7914 107.156 80.9405C107.64 81.066 107.778 81.5763 107.801 82.0783C107.818 82.4631 107.889 82.8454 107.952 83.3619"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M22.5369 11.9698C23.222 12.3128 23.222 12.3128 23.5906 11.595C24.0591 11.4342 24.6253 11.7577 25.049 11.3274C25.5257 11.4463 25.9963 11.6078 26.4801 11.6745C27.2612 11.7818 27.6647 12.3861 28.1058 12.8947C28.4053 13.2402 28.7188 13.5868 28.9926 13.9621C29.3128 14.4012 29.6955 14.7938 30.0169 15.2316C30.3081 15.6284 30.557 16.0571 30.8155 16.4771C30.8872 16.5939 30.9791 16.736 30.9688 16.8586C30.941 17.185 31.0541 17.405 31.286 17.639C31.7321 18.0888 31.6973 18.749 31.8522 19.3107C31.996 19.8342 31.9135 20.4311 31.8672 20.9907C31.8498 21.2044 31.8216 21.6605 31.3511 21.3241C31.3179 21.3001 31.1535 21.4753 31.0404 21.5416C30.9211 21.6112 30.7173 21.7441 30.6751 21.7073C30.1789 21.2715 30.0579 21.583 29.8309 22.0138C29.4971 22.6479 29.2933 22.6011 28.397 22.4412C27.8515 22.3435 27.2733 22.3265 26.9539 21.8531C26.0903 20.5732 25.2056 19.302 25.0859 17.6659C25.0382 17.0102 24.8551 16.326 24.3142 15.8546C23.8482 15.4483 23.5388 14.8676 22.9026 14.641C22.7108 14.5726 22.5704 14.344 22.4213 14.1754C22.1044 13.8159 21.9342 13.4162 21.9259 12.9105C21.9172 12.3852 22.3322 12.2676 22.5369 11.9698"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M95.7508 54.7488C95.1916 54.1897 94.7223 53.6421 94.1752 53.1881C92.6058 51.8859 91.8606 50.0435 90.922 48.3287C90.5004 47.5587 90.6209 46.6939 90.6392 45.8609C90.6425 45.7164 90.8421 45.5759 90.9589 45.4243C91.1184 45.74 91.2679 46.0357 91.4862 46.4673V44.9252C91.8147 44.7625 92.139 44.6738 92.3602 44.4725C92.6348 44.2227 92.945 44.272 93.1968 44.3354C93.4901 44.4091 93.7403 44.6539 94.0352 44.8412C93.8625 45.6505 94.181 46.3281 94.5757 47.0343C94.929 46.9387 95.3461 47.1897 95.6999 46.8268C95.7748 46.7498 96.0209 46.7436 96.1269 46.8074C96.9934 47.3288 98.0567 47.6055 98.4949 48.6758C98.5736 48.8688 98.661 49.1182 98.8192 49.2039C99.0578 49.3332 98.8436 49.7366 99.2533 49.7523C99.5905 49.7652 99.3751 50.109 99.4355 50.2962C99.5105 50.5281 99.6128 50.7551 99.6534 50.9929C99.6907 51.2107 99.6613 51.4402 99.6613 51.6664C98.7939 52.4103 98.2364 53.358 97.809 54.4138C97.1152 54.5264 96.411 54.6412 95.7508 54.7488"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M1.67152 2.08481C1.87737 1.8044 2.03767 1.57079 2.21536 1.35043C2.28039 1.27049 2.38063 1.21416 2.47382 1.16197C2.73933 1.01327 2.92903 1.43369 3.22601 1.25061C3.45879 1.1073 3.73134 0.978481 3.99684 0.9528C4.2172 0.931676 4.544 1.19718 4.66246 1.11185C4.92631 0.921735 5.08412 0.864575 5.31359 1.12179C5.35625 1.16901 5.5124 1.13339 5.60974 1.10978C6.32962 0.936232 6.32921 0.934161 6.71442 1.63375C6.76702 1.48215 6.81258 1.35126 6.89542 1.11227C7.00933 1.42043 7.12116 1.63955 7.16838 1.8715C7.22637 2.15481 7.24045 2.44848 7.25371 2.73842C7.26737 3.03002 7.2566 3.32286 7.42021 3.62316L7.52956 2.53712C7.56808 2.53546 7.60702 2.53381 7.64595 2.53256C7.66708 2.72475 7.70436 2.91694 7.7056 3.10955C7.71181 4.08623 7.66584 5.0654 7.72134 6.03878C7.77063 6.89742 7.62359 7.67487 7.13856 8.38481C6.95672 8.21085 6.78442 7.947 6.57731 8.36783C6.35075 8.82759 5.98791 8.7928 5.51903 8.58197C5.44116 9.08191 5.40595 9.67132 4.57797 9.48286V8.23073C4.52288 8.21996 4.46737 8.20878 4.41229 8.19759C4.28098 8.62463 4.1501 9.05168 4.01507 9.49114C3.64518 9.24345 3.34199 8.98002 3.40205 8.45895C3.41862 8.31274 3.24797 8.15286 3.19288 7.98966C2.95471 7.27972 2.95844 7.27807 2.36903 7.26108C2.25637 7.25777 2.14371 7.26067 2.03104 7.26067H1.72163C1.43584 6.97487 1.1782 6.70026 0.902759 6.44511C0.315836 5.90292 0.129031 5.18511 0.0350071 4.43913C-0.0113834 4.06925 0.0685574 3.6828 0.0159539 3.31458C-0.0420343 2.90866 0.167137 2.60878 0.351871 2.32298C0.720096 1.75345 0.920983 1.73688 1.67152 2.08481"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M67.5463 11.0251C67.0646 11.3524 66.6007 11.6804 66.1173 11.9757C66.0705 12.0043 65.9024 11.8341 65.7209 11.7073C65.6099 11.9066 65.5346 12.0892 65.4169 12.2383C65.2786 12.4144 65.1009 12.5593 64.9439 12.7213C64.6258 13.0489 64.3193 13.4138 63.8492 12.916C63.8131 12.8783 63.7038 12.9156 63.6296 12.9077C63.1015 12.8505 62.5983 12.9822 62.0669 12.5573C61.639 12.2151 61.0943 11.9786 60.6921 11.5586C60.3152 11.1643 59.925 10.794 59.662 10.2937C59.2586 9.52531 58.8601 8.76567 59.0038 7.86395C59.0399 7.6378 59.1952 7.43028 59.3356 7.1275C59.6198 7.36028 59.812 7.51768 60.0364 7.702C60.2204 7.09188 60.1827 6.38277 60.748 5.84514C60.9696 6.01082 61.1838 6.1707 61.4509 6.37034V5.5465C62.1932 5.41975 62.8675 5.1646 63.6114 5.20934C64.038 5.23502 64.4067 5.37005 64.6767 5.62892C65.0238 5.96111 65.4488 6.19886 65.7321 6.62466C65.9881 7.00987 66.3381 7.33212 66.6069 7.72892C67.048 8.38129 67.1972 9.14384 67.5198 9.83804C67.6739 10.169 67.5463 10.6312 67.5463 11.0251"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M19.7064 32.6202V35.0441C19.9313 34.4315 19.8923 33.8127 19.9114 33.1972C19.9188 32.9495 19.8016 32.6413 20.1019 32.4935C20.4122 32.3402 20.7398 32.1886 21.0745 32.1393C21.1896 32.1224 21.4087 32.3949 21.4742 32.5734C21.5446 32.7652 21.4903 33.0025 21.4903 33.2444C21.6775 33.1661 21.789 33.0754 21.8888 33.0866C22.0951 33.1098 22.3784 33.3008 22.484 33.2237C23.0709 32.7917 23.7142 33.0754 24.321 33.0415C24.5956 33.0261 25.011 33.2096 25.1428 33.4325C25.4658 33.9813 26.1178 34.149 26.4595 34.7948C26.4707 35.0706 26.5071 35.4115 26.7938 35.7785C27.1694 36.2594 27.49 36.8567 27.3736 37.5604C27.3194 37.8876 27.3641 38.231 27.3641 38.6299C26.5941 39.0867 25.793 39.5308 25.0251 40.0261C24.2216 40.5447 23.4905 40.1964 22.8067 39.8381C22.3075 39.5763 21.6378 39.4537 21.4692 38.7566C20.3533 38.2546 20.1549 37.0787 19.5593 36.1902C19.1588 35.5929 19.1712 34.8979 19.0577 34.2658C18.9641 33.7435 19.3328 33.1384 19.4968 32.5701C19.5668 32.5867 19.6368 32.6037 19.7064 32.6202"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M41.5633 44.843C41.0878 44.3675 40.5838 43.8634 40.0163 43.296C40.0163 42.9203 39.9774 42.4725 40.0362 42.038C40.0585 41.8765 40.2917 41.7133 40.4653 41.6185C40.5312 41.582 40.7006 41.7353 40.824 41.8028C40.988 41.478 41.0841 41.0386 41.6387 41.1454C41.7419 41.1657 41.8881 41.1719 41.9585 41.1152C42.2348 40.8915 42.5355 40.6633 42.8888 40.7615C43.5221 40.9379 44.2279 41.0411 44.7216 41.478C45.6975 42.3425 46.6253 43.2819 47.1112 44.5303C47.4007 45.2746 47.662 46.0434 47.802 46.8254C47.8629 47.1675 47.7706 47.6372 47.3808 47.9098C46.7392 48.3592 46.1216 48.8446 45.4659 49.2721C45.2427 49.4174 44.9279 49.5181 44.6674 49.4953C43.0259 49.3532 41.8562 48.5808 41.3712 46.7268C41.3003 46.4567 41.1309 46.1755 41.1674 45.9228C41.2204 45.5571 41.42 45.2121 41.5633 44.843"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M44.3797 85.654C44.335 85.4274 44.2902 85.2012 44.2455 84.9747C44.2426 85.8735 43.2937 86.2098 43.087 86.974C43.0132 87.2474 42.609 87.3692 42.4416 87.2172C42.1687 86.9703 41.9827 87.1505 41.8286 87.2507C41.419 87.5175 41.0711 87.4918 40.6527 87.2474C39.447 86.5424 38.2031 85.8946 37.4924 84.6023C36.6358 84.1388 36.3852 83.1973 35.8529 82.4816C35.5941 82.1337 35.5116 81.6544 35.3311 81.1872C35.6458 80.7287 36.1031 80.8501 36.6561 81.1259C36.6027 80.8654 36.6171 80.6256 36.5078 80.4777C36.3566 80.2743 36.5182 80.1944 36.6039 80.1583C36.9932 79.9956 37.3958 79.8763 37.7164 79.5689C37.7947 79.4936 38.0163 79.5234 38.1538 79.5648C38.3995 79.6394 38.6099 79.7963 38.8828 79.5743C38.9603 79.5118 39.2121 79.6369 39.3703 79.7065C40.7302 80.3037 41.9608 81.0526 42.766 82.3781C42.8745 82.557 43.1189 82.7467 43.3015 82.9169C43.8255 83.4036 43.9237 84.1127 44.3292 84.6375C44.5984 84.9867 44.5396 85.2932 44.3797 85.654"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M112.947 32.9885C112.976 32.7802 113.006 32.5714 113.039 32.342C113.121 32.4016 113.194 32.4252 113.213 32.4712C113.503 33.1795 113.864 33.8583 114.034 34.6159C114.141 35.0923 114.277 35.5483 113.816 35.9194C113.502 36.1721 113.821 36.8978 113.114 36.8572C112.781 37.3919 112.248 37.3385 111.738 37.302C111.622 37.6599 111.551 38.0086 111.4 38.3197C111.231 38.6701 110.69 38.7691 110.109 38.6034C109.977 38.5657 109.849 38.4369 109.727 38.4477C108.787 38.5297 108.789 38.5367 108.393 37.7953C108.196 37.4254 107.957 37.0721 107.804 36.6849C107.617 36.2127 107.328 35.9178 106.851 35.714C106.143 35.4112 105.683 34.7973 105.561 34.0671C105.45 33.406 105.76 32.7996 106.35 32.3233C106.642 32.7052 106.934 33.0859 107.343 33.6194C107.343 33.0734 107.337 32.706 107.345 32.3391C107.352 31.9741 107.392 32.0487 107.969 31.7886C108.382 31.6026 108.979 31.8279 109.217 31.2555C109.624 31.2398 110.031 31.2249 110.439 31.2091C111.192 31.1793 111.859 31.2613 112.21 32.098C112.349 32.4294 112.683 32.6795 112.947 32.9885"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M1.5815 38.4769C0.690137 38.2838 0.377001 37.6518 0.295817 37.0963C0.191853 36.386 -0.0487983 35.6897 0.00877567 34.9388C0.0833319 33.9666 0.0779473 32.9804 0.00504786 32.0083C-0.0301592 31.5365 0.272622 31.1873 0.26558 30.7462C0.263924 30.6315 0.423391 30.4095 0.498776 30.414C1.08031 30.4472 1.35659 29.8176 1.96629 29.8138C2.37014 29.8118 2.77191 29.4332 3.22505 29.1963C3.67156 29.6428 4.62132 29.0906 4.98333 30.0752C4.74641 30.7669 5.33665 31.3746 5.5367 32.0832C5.56446 32.1822 5.66842 32.2705 5.66925 32.3641C5.67878 33.4803 5.67505 34.5962 5.67505 35.8086C5.49446 35.6483 5.41617 35.5791 5.22191 35.4064C5.2828 35.6686 5.2712 35.8695 5.36067 35.9374C5.45594 36.0103 5.65682 35.9295 5.79185 35.9747C5.85315 35.995 5.88588 36.1569 5.8925 36.2572C5.89582 36.3031 5.79599 36.4046 5.75954 36.3972C5.48617 36.3437 5.21653 36.2692 4.9212 36.1954C4.71949 36.632 4.5041 37.098 4.34339 37.4463C4.03564 37.4235 3.85173 37.4095 3.66824 37.3958C3.99008 37.7205 3.6202 37.8373 3.48641 38.037C3.35014 38.2395 3.25031 38.4665 3.14221 38.6682C2.43144 38.5912 2.16635 38.1331 1.97623 37.5263C1.84162 37.851 1.72025 38.1422 1.5815 38.4769"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M84.7326 90.4235C84.1482 90.407 83.5952 90.2491 83.3128 90.897C82.8356 90.2682 82.7793 89.8221 83.2651 89.3226C83.6006 88.978 83.8218 88.5476 84.2493 88.2498C84.6233 87.9889 84.7608 87.4119 85.0831 87.0445C85.3307 86.762 85.7027 86.588 86.0196 86.3664C86.1186 86.4629 86.2254 86.5681 86.394 86.7334C86.2151 86.8606 86.0394 86.9857 85.8634 87.1103C85.8829 87.1555 85.9028 87.2006 85.9222 87.2458C86.1799 87.2052 86.4371 87.1646 86.7266 87.119C86.8036 87.2346 86.8931 87.5312 87.0849 87.631C88.2368 88.2307 88.972 89.2319 89.672 90.2595C89.9019 90.5967 89.981 91.0328 90.1657 91.406C90.6217 92.3284 90.7394 92.4987 90.6006 93.337C90.5004 93.943 90.3898 94.5891 89.9139 95.0829C89.7258 95.2775 89.5254 95.5588 89.5154 95.8081C89.4906 96.4377 89.1447 96.5384 88.6361 96.5061C88.494 96.497 88.3436 96.5152 88.2053 96.5525C87.3181 96.791 87.2265 96.7662 86.7842 96.0861C86.1289 95.0791 85.8158 93.9277 85.4347 92.8085C85.1655 92.0178 84.96 91.2047 84.7326 90.4235"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M70.3682 78.0307C69.7407 77.6744 69.1053 77.3626 68.5938 76.8469C67.6407 75.8843 66.6176 74.9826 65.7383 73.957C64.8138 72.8788 63.835 71.816 63.2771 70.5518C63.3359 70.0527 63.9862 70.5829 63.9986 69.9939C64.0024 69.8257 64.4145 69.6634 64.6431 69.5039C65.2106 69.1079 65.5275 69.0417 65.9408 69.4815C66.3488 69.916 66.8206 70.0718 67.3545 70.1849C68.1792 70.3597 68.7483 70.993 69.4541 71.3827C70.2092 71.7994 70.7472 72.4704 71.3607 73.0532C71.6783 73.3547 72.0731 73.5863 72.346 73.9201C72.6206 74.256 72.8729 74.6599 72.9702 75.0728C73.0291 75.3243 72.8402 75.7037 72.648 75.9278C72.4107 76.204 72.2984 76.6029 71.883 76.7367C71.6427 76.8137 71.6767 77.0821 71.6299 77.3033C71.576 77.5572 71.5052 77.8662 71.0645 77.5473C70.7563 77.3249 70.497 77.6405 70.3682 78.0307"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M115.845 71.4973C114.558 70.9671 114.004 69.9813 113.454 69.0232C112.971 68.1812 112.53 67.3043 112.171 66.4026C111.812 65.5021 111.187 64.6489 111.466 63.5156C112.28 64.0831 112.213 65.1679 112.995 65.8931C112.852 64.7458 112.256 63.8594 111.959 62.6508C112.37 62.8761 112.519 62.9577 112.702 63.0575C112.737 62.8608 112.774 62.6545 112.81 62.449C113.151 62.3844 113.487 62.3206 113.883 62.2453C113.989 62.4134 114.126 62.6619 114.291 62.8922C114.93 63.7882 114.934 63.784 116.095 64.197C116.225 64.2434 116.346 64.3187 116.464 64.3933C117.363 64.9616 118.182 65.6019 118.677 66.5898C118.86 66.9551 119.11 67.6261 119.099 68.0151C119.096 68.1062 119.172 68.2131 119.239 68.2901C119.408 68.486 119.331 68.6529 119.157 68.7519C118.649 69.0382 118.429 69.6015 117.979 69.9386C117.786 70.0824 117.752 70.2737 117.717 70.5111C117.669 70.8341 117.035 71.2529 116.741 71.185C116.558 71.1427 116.44 70.8072 116.191 71.0545C116.06 71.1845 115.961 71.3461 115.845 71.4973"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M79.2642 45.1725C79.067 45.2052 78.8604 45.2391 78.575 45.2864C78.6876 45.4976 78.768 45.6476 78.8521 45.8049C78.3157 46.3413 77.7573 46.8997 77.1816 47.4758C77.0888 47.4758 76.9753 47.4589 76.8685 47.4783C75.6014 47.7128 74.7577 46.9937 74.054 46.1268C73.5043 45.4496 73.0317 44.7036 72.6639 43.8897C72.4344 43.3815 72.2294 42.9134 72.3934 42.2229C72.7778 43.0679 73.1204 43.8201 73.4629 44.5727C73.5238 44.5528 73.5847 44.5334 73.646 44.5135C73.6182 44.3702 73.6141 44.2165 73.5586 44.0848C73.3295 43.5405 73.069 43.0087 72.8532 42.4599C72.7575 42.2167 72.5525 41.9139 73.0748 41.8009C73.2359 41.7661 73.3304 41.4186 73.4534 41.2127C73.5611 41.0321 73.6654 40.8494 73.7508 40.7036C74.2789 40.6552 74.2839 41.117 74.6131 41.3076C74.5365 41.0168 74.4599 40.726 74.3588 40.3433C74.5278 40.2095 74.7536 40.0306 74.9793 39.8512C75.1218 39.9929 75.3107 40.2186 75.4859 39.8023C75.676 39.3525 75.9568 39.1773 76.412 39.4726C76.4534 39.4996 76.5392 39.5203 76.5665 39.4979C77.0938 39.0634 77.4044 39.4963 77.6484 39.8284C78.2308 40.6225 78.505 41.576 78.8537 42.4831C78.9357 42.696 79.1143 43.1959 78.5137 43.2199C78.4797 43.2212 78.4536 43.408 78.4242 43.5082C78.5493 43.5384 78.7415 43.6354 78.7891 43.5873C79.1259 43.2497 79.3073 43.6905 79.2741 43.7679C79.0716 44.2438 79.5409 44.7036 79.2642 45.1725"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M75.1738 21.0679C75.3064 21.2004 75.4393 21.3334 75.6411 21.5347C75.6779 21.2154 75.7086 20.9519 75.7421 20.6645C76.2069 20.5671 76.6861 20.4445 77.1728 20.3725C77.4669 20.329 77.7775 20.3302 78.0708 20.3754C78.2944 20.4102 78.1188 20.8268 78.5359 20.8633C78.8055 20.8869 79.0127 21.345 79.2044 21.6639C79.3602 21.9228 79.127 22.4832 79.7184 22.4497C79.7387 22.8162 79.759 23.1832 79.7802 23.5498C79.7818 23.5854 79.7901 23.6206 79.7955 23.6562L81.4738 25.3346C81.6536 25.3346 81.8441 25.3114 82.026 25.34C82.3064 25.3851 82.6083 25.6631 82.4646 25.8354C82.1448 26.2185 82.7181 26.4832 82.4907 26.7959C81.6171 27.0577 81.3417 27.0867 80.6309 26.9624C80.809 27.3472 80.964 27.6827 81.1586 28.1044C81.0451 28.2133 80.8956 28.4788 80.7482 28.478C79.8174 28.4709 78.8379 28.707 78.0082 28.0464C77.7833 27.867 77.5116 27.7266 77.3368 27.5075C76.9379 27.008 76.5809 26.4749 76.2168 25.948C76.0374 25.6883 75.8842 25.41 75.7119 25.1449C75.4451 24.7344 75.5242 24.1429 75.0351 23.8493C75.1092 23.3514 74.8284 22.9749 74.649 22.5454C74.4051 21.9618 74.5563 21.4034 75.1738 21.0679"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M40.3117 4.32349C40.752 4.32349 41.0532 4.32307 41.3539 4.32349C41.7569 4.32432 42.1931 4.2568 42.2854 4.83917C42.2954 4.90379 42.4461 5.00278 42.5182 4.99242C42.9954 4.9216 43.1192 5.37266 43.4112 5.57106C44.2036 6.10952 44.3204 6.99633 44.5184 7.81645C44.6315 8.28408 44.4803 8.61958 43.948 8.9381C43.3507 9.29556 42.6031 9.51757 42.1931 10.167C41.831 10.1741 41.5349 10.7403 41.112 10.2872C41.0507 10.2217 40.9148 10.1998 40.8142 10.2014C39.3885 10.2288 38.4963 9.41029 37.7512 8.31887C37.373 7.7655 36.8996 7.27094 36.7513 6.58958C36.6904 6.31 36.6548 6.02337 36.6349 5.73799C36.6278 5.64438 36.6829 5.48201 36.7484 5.4584C37.322 5.25337 37.7391 4.7642 38.2954 4.56497C38.9813 4.31976 39.7149 4.24603 40.3117 4.32349"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M38.5009 59.1168C38.6662 59.3765 38.7876 59.5678 39.0237 59.9394C39.0767 59.5459 39.097 59.4113 39.1123 59.2762C39.162 58.8285 39.1612 58.8293 39.727 58.7717C39.7978 58.7643 39.9067 58.7738 39.932 58.7336C40.1901 58.3269 40.5931 58.213 40.9998 58.3356C41.4608 58.4743 41.9558 58.6483 42.3145 58.9507C43.7141 60.1303 44.5375 61.7113 45.177 63.3888C45.2856 63.675 45.1924 64.0379 45.1924 64.361C45.0246 64.3423 44.8929 64.3278 44.7608 64.3129C44.7893 64.718 44.6978 65.0183 44.224 65.114C44.0819 65.143 43.8876 65.355 43.8735 65.4979C43.8259 65.9859 43.3247 65.7481 43.1499 66.002C42.8708 65.5576 42.3903 66.0956 42.0763 65.7779C41.7756 65.4739 41.3639 65.2395 41.1651 64.8824C40.7273 64.0959 40.3081 63.2774 40.0517 62.4208C39.9208 61.9826 39.7266 61.6914 39.389 61.4926C38.841 61.1708 38.4152 60.7628 38.1476 60.1829C37.9244 59.6987 37.9148 59.7033 38.5009 59.1168"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M59.6719 45.9786C59.6719 45.8664 59.645 45.7102 59.6814 45.5702C59.7059 45.4766 59.8662 45.4128 59.8803 45.3229C59.8956 45.2248 59.7804 45.1121 59.7792 45.0052C59.7784 44.9104 59.9117 44.794 59.8857 44.724C59.838 44.5952 59.7312 44.4759 59.6214 44.3864C59.5485 44.3268 59.4271 44.326 59.2772 44.2854C59.3476 44.5302 59.4043 44.7273 59.4615 44.9249C59.0626 44.6817 58.6194 44.4879 58.8145 43.9018C58.9794 43.9722 59.1413 44.0422 59.3422 44.1284C59.4068 43.423 58.7528 43.79 58.501 43.4561C58.8696 43.4996 59.1152 43.2457 59.4859 43.295C59.6578 43.3178 59.8815 42.9525 60.1449 42.7031C60.5107 43.0017 60.9207 43.336 61.4004 43.7274C61.4472 43.4412 61.4807 43.2374 61.5213 42.9893C62.0635 42.8845 62.6194 42.7773 63.1814 42.6687C63.4701 43.0374 63.6959 43.3737 63.9709 43.6632C64.2095 43.9134 64.5375 44.0803 64.7674 44.3367C65.4161 45.0607 65.7101 45.9749 65.9769 46.8791C66.0726 47.2026 66.1778 47.7145 65.5594 47.8011C65.5623 48.3951 64.936 48.4837 64.6535 48.8602C64.2994 49.3316 63.6731 49.4128 62.9971 49.1398C61.9848 48.731 61.3196 47.9407 60.673 47.1711C60.3496 46.7855 59.9863 46.4218 59.6719 45.9786"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M78.2878 60.6276C78.4701 60.6897 78.6461 60.7493 78.8478 60.8181C78.8888 59.8679 77.9068 59.6016 77.7701 58.7268C77.9689 58.8146 78.1308 58.8519 78.2481 58.9451C78.4361 59.095 78.5943 59.2814 78.8288 59.5158C78.7488 59.0395 78.6958 58.9302 78.4241 58.6042C79.0181 57.886 79.0181 57.886 79.7193 57.8835C80.1049 58.318 80.4342 58.8904 80.9283 59.1919C81.4739 59.5254 81.6346 60.0945 82.0368 60.5025C82.4211 60.8931 82.6763 61.4249 82.931 61.924C83.071 62.1974 83.1899 62.5465 83.1443 62.834C83.0863 63.1973 82.9314 63.7312 82.6746 63.8343C82.2521 64.0045 82.3466 64.3032 82.2136 64.56C82.0314 64.9108 81.782 65.2521 81.3247 65.3275C81.0576 65.3714 80.7395 65.5752 80.5436 65.487C80.0668 65.272 79.5743 64.9982 79.2218 64.6225C78.5566 63.9134 77.9618 63.1335 77.3927 62.3432C77.2498 62.1452 77.3157 61.7973 77.2734 61.4058C77.4631 61.5591 77.5385 61.6196 77.6984 61.7484C77.6156 61.1722 78.1192 60.9747 78.2878 60.6276"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M72.349 102.057C72.0404 101.887 71.8917 101.806 71.7475 101.726C71.4936 102.644 71.4307 102.691 70.6806 102.361C70.8785 102.822 71.0372 103.19 71.2099 103.591C71.014 103.705 70.8135 103.821 70.611 103.939C70.2448 103.573 69.8733 103.202 69.4674 102.796C69.223 103.346 69.8956 103.6 69.8294 104.132C69.2259 104.216 68.8759 103.805 68.5284 103.428C68.3387 103.221 68.2359 102.933 68.0404 102.735C67.169 101.85 66.3861 100.894 65.6563 99.8911C65.5909 99.8013 65.5001 99.7292 65.419 99.6513C64.9791 99.2317 64.5181 98.8262 64.4854 98.1424C64.9244 97.8736 65.1576 98.2878 65.4562 98.5442C65.7598 98.0417 65.0574 97.9746 65.0888 97.6043C65.1158 97.1578 65.9653 97.7274 65.7495 96.9975H66.9726C67.3226 97.244 67.6776 97.4879 68.0255 97.741C68.3747 97.9949 68.6054 98.3598 69.0329 98.5665C69.4479 98.7678 69.7229 99.2425 70.0883 99.5643C70.3264 99.7743 70.4776 100.063 70.8583 100.157C71.1337 100.225 71.2807 100.643 71.6991 100.589C71.8155 100.574 72.0255 100.785 72.0847 100.934C72.1978 101.219 72.2326 101.534 72.349 102.057"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M64.5875 26.5067C64.976 26.5324 65.2444 26.3315 65.5998 26.5879C65.4192 26.65 65.2883 26.6952 65.1455 26.7444C65.2788 27.1972 65.4271 27.647 65.536 28.1059C65.5638 28.2236 65.5021 28.4559 65.4205 28.4903C64.9673 28.6817 64.8302 29.1692 64.4773 29.4363C64.3212 29.5548 64.0872 29.5933 63.883 29.6165C63.7807 29.6277 63.6601 29.4732 63.5578 29.484C63.4331 29.4972 63.3188 29.6062 63.1875 29.6807C62.9937 28.9956 63.0036 28.9679 62.2402 28.7078C61.7834 28.552 61.6885 28.103 61.3646 27.8205C61.2921 27.975 61.2221 28.1242 61.1439 28.2915C61.0299 28.1722 60.8382 28.0637 60.8386 27.956C60.8444 26.6102 60.8431 26.58 60.2289 25.7736C59.8826 26.382 60.5462 26.7341 60.5822 27.3293C60.4178 27.3036 60.1721 27.3227 60.1436 27.2527C59.8549 26.551 59.415 25.8883 59.866 25.0466C60.006 24.7853 60.0313 24.6482 60.3457 24.6428C60.5395 24.6399 60.7479 24.526 60.9206 24.4166C61.3683 24.1337 61.7995 23.8256 62.2779 23.4996C62.3873 23.6628 62.4883 23.814 62.4639 23.7771C62.8412 24.0401 63.2347 23.3318 63.2977 24.0704C63.3159 24.28 63.7844 23.78 63.7844 24.3288C63.7844 24.5409 64.1741 24.7534 64.3701 24.9493C64.3001 25.1307 64.2338 25.3039 64.1671 25.477C64.2226 25.5155 64.2781 25.554 64.334 25.5926C64.4322 25.4057 64.5304 25.2189 64.6542 24.9841C64.8559 25.3271 64.9731 25.5255 65.1268 25.786C64.9599 26.0088 64.7739 26.2578 64.5875 26.5067"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M26.6178 60.2475C26.3576 59.9195 26.1518 59.6598 25.9232 59.3707C25.8068 59.6088 25.7326 59.76 25.6361 59.9572C25.2016 59.7534 24.9092 59.4171 24.6603 59.0662C24.1102 58.2904 23.6848 57.4347 23.1273 56.6576C22.7843 56.1801 22.764 55.5799 22.8995 54.9586C23.4143 54.8542 23.5258 55.4594 23.9549 55.6122V54.5125C24.7659 54.3982 25.5475 54.288 26.264 54.1873C27.0158 54.8625 27.5108 55.5919 27.8616 56.4344C28.0621 56.9144 28.475 57.2748 28.6005 57.824C28.6503 58.0411 28.3719 58.3331 28.7145 58.4946C28.7203 58.4971 28.6126 58.7614 28.6092 58.7601C28.0501 58.5584 27.862 59.3694 27.324 59.2394C27.2892 59.2307 27.1939 59.4386 27.1405 59.5525C27.0813 59.6776 27.0547 59.8209 26.9818 59.936C26.928 60.0222 26.8236 60.076 26.6178 60.2475"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M51.6375 73.9093C51.799 74.2829 51.9166 74.555 52.0848 74.9431C52.1917 74.6602 52.2409 74.5306 52.2931 74.3931C52.3437 74.4241 52.4265 74.4457 52.4373 74.4863C52.5392 74.8735 52.7231 75.2045 53.0027 75.4986C53.17 75.6746 53.2909 75.9012 53.4048 76.1195C53.6057 76.5059 53.8907 76.7698 54.3521 76.8518C54.4246 76.7051 54.4992 76.5535 54.534 76.4831C54.7477 76.643 54.9801 76.8174 55.1532 76.947C55.1532 77.0879 55.1681 77.1483 55.1511 77.1595C54.9465 77.2925 54.7373 77.418 54.5464 77.5348C54.6019 77.8434 54.6516 78.123 54.7266 78.5417C54.3882 78.3773 54.203 78.287 53.9363 78.1569C53.7884 78.4543 53.6401 78.7534 53.4806 79.0748C53.3291 79.0918 53.1514 79.1125 52.9339 79.1369V79.6389C52.3664 80.0639 51.9021 80.0067 51.4101 79.5582C50.8741 79.0694 50.2698 78.6564 49.723 78.0745C49.9529 77.9225 50.1749 77.7759 50.4185 77.6151C50.2942 77.1595 50.0709 76.7528 49.7491 76.3551C49.4273 75.9571 49.2508 75.441 49.0193 74.9928C49.3502 74.5848 49.6116 74.8868 49.9152 75.0144C49.928 74.9005 49.9806 74.7791 49.9446 74.6971C49.718 74.1876 49.8162 73.9358 50.2963 73.9138C50.7469 73.8927 51.1992 73.9093 51.6375 73.9093"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M19.488 78.3759C19.6773 78.6559 19.8318 78.8849 20.0248 79.1703C20.0749 79.0142 20.1437 78.9135 20.1279 78.8294C20.0509 78.4215 19.9511 78.018 19.8467 77.5578H20.5032C20.56 77.6759 20.6295 77.8205 20.7671 78.1067V77.1838C20.8955 77.1387 21.0048 77.125 21.0814 77.0683C21.2566 76.9378 21.5342 76.6416 21.5627 76.6648C21.8498 76.9009 22.2043 76.7584 22.4827 76.8653C22.8977 77.0244 23.292 77.3019 23.2866 77.8312C23.285 77.9894 23.0754 78.1655 23.1069 78.2984C23.1326 78.4065 23.4225 78.4306 23.5091 78.5528C23.5799 78.6526 23.5857 78.9202 23.5128 78.9786C23.22 79.2122 23.2846 79.5145 23.3045 79.7978C23.3297 80.1516 23.1748 80.3665 22.8608 80.4556C22.5253 80.5509 22.4471 80.7658 22.3766 81.0868C22.2768 81.5404 21.9658 81.8419 21.4397 81.8196C21.2579 81.8121 21.0694 81.8163 20.893 81.8548C20.444 81.9529 19.8782 81.8452 19.7382 81.516C19.3965 80.7124 18.9019 79.9532 18.9939 79.0076C19.0299 78.6389 19.2519 78.5341 19.488 78.3759"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M55.7132 58.0535C55.994 58.136 56.2872 58.2217 56.6476 58.3273C56.8004 57.9632 56.8456 57.6137 56.5233 57.2885C56.9193 56.9286 57.1827 57.4712 57.5708 57.4124C57.6069 57.2164 57.6454 57.0102 57.6827 56.808C57.9867 56.4825 58.2609 57.0831 58.6283 56.7998C59.004 56.5098 59.0988 57.1357 59.4182 57.2073C59.5975 57.2475 59.7653 57.4343 59.8933 57.5917C60.3174 58.1119 60.3837 58.848 60.9549 59.3024C61.0916 59.4109 61.0187 59.7841 61.0493 60.1159C60.416 59.8048 60.3775 60.8096 59.7674 60.5715C59.5797 60.8751 59.757 61.4256 59.0707 61.4914C58.9982 61.368 58.8847 61.1746 58.7232 60.8987C58.5856 61.1857 58.519 61.3249 58.4506 61.4682C58.0662 61.5593 57.8902 61.228 57.7639 61.0172C57.3443 60.3151 56.8008 59.7779 56.0979 59.3579C55.6655 59.0994 55.4282 58.6782 55.7132 58.0535"/>
					<path fill-rule="evenodd" clip-rule="evenodd" d="M50.217 28.042C49.6839 28.4595 49.2909 28.7676 48.7835 29.1657H47.8345C47.4651 28.6314 47.345 27.9285 46.8003 27.4874C46.7431 26.7434 46.2287 26.2824 45.7818 25.7639C45.6397 25.5986 45.6703 25.2846 45.6099 24.9773C45.7731 24.9317 45.9346 24.935 46.0191 24.8559C46.886 24.0453 47.7028 24.501 48.3937 25.0539C48.9835 25.5257 49.4814 26.1499 49.8993 26.7853C50.1363 27.1452 50.13 27.665 50.217 28.042"/>
				</svg>
				</figure>
				<!-- Svg END -->

				<!-- Svg START -->
				<figure class="position-absolute bottom-0 end-0 mb-n3 me-n3 d-none d-xl-block z-index-9"> 
					<svg class="fill-warning" width="169" height="97" viewBox="0 0 169 97">
						<path  fill-rule="evenodd" clip-rule="evenodd" d="M145.181 2.30937C145.194 2.35994 145.206 2.41052 145.22 2.4606H153.005C153.001 2.41052 152.998 2.35994 152.994 2.30937H145.181ZM69.2583 62.9634C71.8715 60.3904 74.731 58.0116 76.1165 54.4721C73.8306 57.303 71.5447 60.1329 69.2583 62.9634V62.9634ZM82.658 33.6429C82.658 33.1381 82.699 32.6293 82.6519 32.1291C81.8942 24.0652 75.29 21.9823 69.3919 23.6251C67.4687 24.1602 65.8485 25.2047 64.2996 26.3438C62.9192 27.3584 61.5458 28.4813 60.479 29.8059C57.8168 33.1128 56.2983 37.0085 55.4834 41.1378C54.3498 46.8826 54.1196 52.6264 56.2952 58.2251C57.5694 61.5016 59.4441 64.3149 62.5337 66.2075C63.4225 66.7518 63.9946 66.596 64.681 65.9354C69.7192 61.0879 74.3526 55.9131 77.7797 49.7651C80.5775 44.7476 82.6079 39.4909 82.658 33.6429V33.6429ZM128.768 5.63447C132.897 4.68003 137.025 3.7261 141.154 2.77166C137.918 3.25065 134.699 3.8662 131.503 4.58443C130.566 4.79485 129.695 5.2971 128.791 5.66228C126.869 5.62435 125.412 6.74216 123.907 7.73402C125.527 7.03451 127.148 6.33449 128.768 5.63447V5.63447ZM61.3243 68.8918C56.232 65.6901 53.0756 61.2209 51.6157 55.7239C48.825 45.214 50.4376 35.3702 57.1476 26.6801C60.2984 22.5989 64.633 20.0471 69.796 19.2859C74.1549 18.6435 77.9663 20.0967 81.189 23.0399C84.395 25.9669 86.4634 29.6188 86.8104 33.9282C87.1073 37.621 86.7801 41.3715 85.3637 44.8827C84.2301 47.6914 83.0657 50.4996 81.6792 53.1874C80.8441 54.8064 79.6053 56.2312 78.4651 57.6778C75.7852 61.0762 73.0557 64.4352 70.3879 68.1028C71.3869 67.817 72.4284 67.6303 73.3769 67.2257C76.4377 65.9192 78.887 63.7615 81.0757 61.3205C86.3486 55.4392 89.8687 48.4814 93.1946 41.4053C96.087 35.2508 99.0305 29.1206 102.992 23.5492C110.751 12.6372 121.122 5.68302 134.22 2.76054C142.242 0.970524 150.362 1.27552 158.484 1.3084C161.54 1.32053 164.599 1.07269 167.656 0.949281C167.823 0.9422 167.993 0.992273 168.349 1.04184C167.979 1.38882 167.731 1.62148 167.681 1.66802C168.116 2.02157 168.558 2.38169 169 2.74131C168.621 3.19248 168.326 3.81158 167.842 4.05487C167.124 4.4155 166.283 4.62287 165.477 4.69571C163.262 4.8955 161.037 4.96985 158.818 5.13322C156.285 5.32037 153.756 5.56467 151.222 5.74928C150.607 5.7943 149.974 5.63042 149.362 5.6901C146.433 5.97537 143.486 6.17466 140.588 6.65668C137.986 7.09015 135.459 7.97225 132.859 8.42899C130.878 8.77697 129.059 9.47497 127.248 10.264C122.892 12.1633 118.74 14.3109 115.146 17.5733C110.104 22.1487 106.091 27.5132 102.596 33.2469C100.514 36.664 99.1741 40.5268 97.3748 44.1265C95.5164 47.8436 93.5355 51.501 91.5501 55.1529C90.5496 56.993 89.5814 58.8877 88.3092 60.534C86.686 62.6356 84.824 64.5632 82.9615 66.4645C81.7525 67.6971 80.4707 68.9242 79.0256 69.8457C75.6719 71.9863 71.9767 72.6357 68.101 71.5568C66.9183 71.2281 66.0746 71.3378 65.1165 72.178C58.0277 78.3947 50.1194 83.3662 41.5182 87.193C36.3864 89.4767 31.238 91.7866 25.9288 93.5888C19.0807 95.9129 11.9788 97.2088 4.68305 96.9048C3.50343 96.8557 2.30612 96.6266 1.17506 96.2862C0.704633 96.1446 0.386966 95.4936 0 95.0748C0.424398 94.7911 0.825022 94.3232 1.27876 94.2645C2.05269 94.1644 2.86102 94.3116 3.65266 94.3738C4.18783 94.4158 4.72706 94.5791 5.25161 94.5361C10.9094 94.0688 16.4327 92.8792 21.8072 91.0993C35.8088 86.4616 48.6368 79.6577 59.9504 70.1179C60.3667 69.7668 60.7643 69.3925 61.3243 68.8918V68.8918Z"/>
					</svg>            
				</figure>
				<!-- Svg END -->

				<!-- Tabs content START -->
				<div class="tab-content p-0 mb-0" id="v-pills-tabContent">
					<div class="tab-pane fade show active" id="step1" role="tabpanel" aria-labelledby="step-1">            
						<!-- Image -->
						<img src="assets/images/AdobeStock_327182618.jpeg" class="rounded-3" alt="">          
					</div>

					<div class="tab-pane fade" id="step2" role="tabpanel" aria-labelledby="step-2">
						<!-- Image -->
						<img src="assets/images/AdobeStock_392742050.jpeg" class="rounded-3" alt="">
					</div>

					<div class="tab-pane fade" id="step3" role="tabpanel" aria-labelledby="step-3">
						<!-- Image -->
						<img src="assets/images/AdobeStock_365567569.jpeg" class="rounded-3" alt="">
					</div>   

				</div>
				<!-- Tabs content END -->
			</div>            
		</div><!-- Row END -->
	</div>
</section>
<!-- =======================
Step END -->

<!-- =======================
Pricing plan START -->
<section class="bg-light position-relative price-wrap py-5" id="get-started">

	<!-- Svg START -->
	<figure class="opacity-25 mb-0 position-absolute top-0 end-0 d-none d-lg-block">  
		<svg class="fill-dark" width="233" height="209">
			<path d="m42.126 51.038c-6.1 0-10.4-3.9-10.8-9.7-0.3-3.4 0.7-6.5 2.6-9.3 2-2.8 6.4-4.9 9.9-2.8 0.3 0.2 0.7 0.3 1.1 0.4 4.6 0.5 8.7 5.6 8.6 10.9-0.1 5.1-4.3 9.5-9.7 10.3-0.6 0.1-1.3 0.2-1.7 0.2z"/>
			<path d="m90.426 20.638c-6.9 0-11.4-5.6-9.8-12.4 0.5-2.3 1.6-4.4 3.3-6 1.9-1.8 4.1-2.7 6.8-2 1.2 0.3 2.4 0.3 3.5 0.6 4 0.8 6.8003 3.2 7.8003 7.2 1.1 4-0.4 7.2-3.4003 9.8-2.3 2-5.1 2.8-8.2 2.8z"/>
			<path d="m23.626 79.538c-0.1 6.7-6.4 11-12.5 8.4-8.4-3.5-9.2-12.6-5.5-18.4 0.9-1.4 2.2-2.3 3.8-2.8 1.4-0.4 2.9-0.5 3.9 0.4 1.6 1.5 3.6 2 5.3 3.1 3.1 2 5 5.5 5 9.3z"/>
			<path d="m37.626 182.54c-7.3 0-12.7-5.8-12.3-12.5 0.3-4.7 3.3-7 7.9-5.9 0.7 0.2 1.4 0.1 2.1 0.2 1.3 0.1 2.7 0.1 4 0.3 4.6 0.8 7.9 4.5 7.9 8.9 0 4.1-3.3 7.9-7.7 8.9-0.7 0-1.5 0-1.9 0.1z"/>
			<path d="m19.326 124.74c0 3.6-1.1 6.6-3.5 9-3.3 3.3-8.1 3.6-11.7 0.6-4.5-3.6-5.5-11.1-2.1-15.6 2.5-3.3 6.1-3.9 9.9-3.1 3.9 0.8 6.2 3.4 7.1 7.3 0.2 0.7 0.3 1.4 0.3 1.8z"/>
			<path d="m125.73 197.94c0-5.2 3.9-9 9.4-9 6.4 0 11 4.2 11 10.1 0 5.2-4.5 9.4-10 9.5-5.9 0-10.4-4.6-10.4-10.6z"/>
			<path d="m83.126 206.74c-6.3 0-12.4-6.1-12.3-12.4 0-4.4 3.4-6.8 7.6-5.5 1 0.3 2.2 0.3 3.3 0.3 4.6-0.2 8 1.9 9.5 5.8 2.3 5.9-1.7 11.9-8.1 11.8z"/>
			<path d="m202.63 178.74c0 4.4-3.7 8.3-8.3 8.8-4 0.4-8.2-2-9.7-5.7-1-2.4-0.9-4.7 0.6-6.8 0.1-0.2 0.3-0.4 0.4-0.6 3.4-4.7 8.5-5.6 13.4-2.4 2.3 1.6 3.6 4 3.6 6.7z"/>
			<path d="m124.73 13.538c0-2.1 0.5-3.8 1.6-5.4 2-3 5.2-3.8 8.4-2.1 1.3 0.7 2.5 1.4 3.7 2.3 2.6 2.1 3.7 4.8 2.9 8.1-0.8 3.4-3.1 5.5-6.6 6.2-3.3 0.6-6-0.6-8-3.2-1.4-1.8-2-3.8-2-5.9z"/>
			<path d="m222.83 126.14c5.3-0.1 9.4 4.3 9.3 9-0.1 2.8-1.1 5.1-3.2 7-4.4 4-11.1 1.9-12.4-3.9-0.3-1.3-0.4-2.8 0-4 0.6-2 1.6-4 2.6-5.9 1-1.6 2.7-2.2 3.7-2.2z"/>
			<path d="m146.03 79.538c0-0.3-0.1-0.7-0.1-1.1-0.2-3.3 1.6-5.5 4.7-6.2 4.3-0.9 9.1 2 10 6.1 1 4.3-1.8 8.5-6.2 9.6-4.5 1.1-9.4-2.3-8.6-7.4 0.1-0.3 0.1-0.6 0.2-1z"/>
			<path d="m65.926 61.838c0.1-3.1 0.9-5.5 2.9-7.3 3.4-3.1 8.1-2 9.6 1.7 0.4 0.9 0.9 1.7 1.4 2.5 1.4 2.7 1.5 5.4-0.3 7.9-1.7 2.4-4.1 3.5-7.1 3-3.2-0.5-5.1-2.5-6.1-5.4-0.2-1-0.3-1.9-0.4-2.4z"/>
			<path d="m104.23 149.94c2.7 1.2 6.2 2 8.1 5.3 1.5 2.7 0.9 6-1.4 8.4-2.4 2.4-5.9 3-8.8 1.6-4.2003-2.1-6.0003-7.9-3.7003-12 1.1-2.1 3.0003-3.3 5.8003-3.3z"/>
			<path d="m147.63 158.34c-4.3 0-7.8-3.6-7.6-7.9 0.1-1.7 0.6-3.5 1.4-5 1.2-2.4 3.5-3.3 6-2.8 1.7 0.3 3.4 1 4.8 2 3 2 4.1 5.3 3.1 8.3-1 3.2-4.3 5.4-7.7 5.4z"/>
			<path d="m48.226 92.838c0-2.2 0.6-4.1 2.2-5.6 2.5-2.3 6.1-2.1 8.2 0.5 0.7 0.9 1.4 1.7 2.2 2.5 1.2 1.2 2.1 2.6 2.5 4.3 1 4.7-2.9 8.7004-7.6 7.8004-4.1-0.7-7.4-4.9004-7.5-9.5004z"/>
			<path d="m174.53 41.738c-2.9 0-5.4-1.8-6.1-4.7-0.3-1.3-0.8-2.5-1.7-3.6-2.1-2.5-1.3-6 1.6-7.5 0.6-0.3 1.3-0.6 2-0.7 4.7-0.6 10.3 3.7 10.8 8.4 0.5 4.3-2.6 8.1-6.6 8.1z"/>
			<path d="m107.63 50.838c0 2.4-0.4 4.2-1.6 5.9-2.5 3.6-7.4003 3.9-10.3 0.5-2.4-2.7-2.6-6.5-0.7-9.5 0.4-0.7 0.8-1.4 1.1-2.1 1.6-4 6.1003-4.9 9.0003-1.7 2 2.1 2.5 4.6 2.5 6.9z"/>
			<path d="m205.43 62.638c0 3.8-2.8 6.8-6.5 7.1-4 0.3-7.5-2.6-7.9-6.7-0.2-1.5-0.1-3 0-4.5 0.3-2.6 2.4-4.4 5.1-4.6 4.5-0.4 9.4 4.2 9.3 8.7z"/>
			<path d="m226.63 92.038c0 3.8-3 7.2-6.9 7.6-3.6 0.4004-7.1-2-7.8-5.6-0.5-2.4 0.1-4.8 1.1-6.9 0.4-0.9 1.5-1.7 2.4-2.2 4.7-2.3 11.2 1.8 11.2 7.1z"/>
			<path d="m180.03 117.24c0 3.3-2.1 6.1-5.3 6.8-3 0.7-6-0.9-7.4-3.9-0.4-0.8-0.9-1.7-1.5-2.4-2.1-2.9-1.1-6.7 2.2-8.2 5.2-2.3 12 2.1 12 7.7z"/>
			<path d="m131.73 58.138c0 0.3 0 0.7-0.1 1.2-0.5 3.4-2.9 5.8-6 5.8-3 0-5.5-2.2-6.1-5.4-0.3-1.8-0.7-3.6-1-5.4-0.4-2.1 0.1-4 1.9-5.3 1.9-1.4 3.9-1.3 5.9-0.2 2.7 1.4 5.4 5.9 5.4 9.3z"/>
			<path d="m77.626 136.04c-0.2 2.6-1.5 4.8-4.2 6s-5.3 0.8-7.6-1.2c-2.7-2.3-3.6-6.6-2.1-9.9s5.2-4.6 8.5-2.9c3.4 1.7 5.4 4.6 5.4 8z"/>
			<path d="m101.03 93.738c-0.1 1.5-0.1 2.5-0.2 3.4-0.4 2.4-1.8003 4.0004-4.2003 4.7004-2.3 0.6-4.3-0.1-5.8-1.8-2.8-3.0004-2.5-8.2004 0.3-11 1.9-1.8 4.6-2.3 6.9-1.2 2.2003 1 3.2003 3.1 3.1003 5.7-0.1 0.3-0.1 0.5-0.1 0.2z"/>
			<path d="m126.23 130.24c0 2.6-1.9 4.8-4.6 5.4-2.6 0.6-4.9-0.1-6.8-2.1-1.8-2-2.4-4.3-1.7-6.9 0.6-2.2 2.1-3.6 4.3-4.1 2.1-0.5 3.9 0.2 5.4 1.8 0.6 0.7 1.3 1.4 1.9 2.1 1.1 1.1 1.6 2.3 1.5 3.8z"/>
			<path d="m100.73 119.84c-0.1 3.2-1.1003 5.1-3.3003 6.2s-4.4 0.8-6.3-0.7c-2.9-2.2-3.6-6.7-1.7-9.8 2.3-3.7 7.3-3.7 9.5 0.1 0.9 1.4 1.4003 3.2 1.8003 4.2z"/>
			<path d="m137.03 101.04c0 3-1.7 5.5-4.3 6.2s-5.4-0.5-6.8-3.1c-0.9-1.6-1.3-3.4-0.9-5.3004 0.5-2.4 1.9-4 4.3-4.6 2.3-0.6 4.2 0.2 5.8 1.9 1.3 1.3 1.8 3.1 1.9 4.9004z"/>
			<path d="m121.53 89.338c-3.3 0-6.3-3.1-6.3-6.5 0-3 2.3-5.3 5.3-5.2 3.9 0 6.9 2.6 6.9 5.8 0 3.1-2.7 5.9-5.9 5.9z"/>
		</svg>
	</figure>
	<!-- Svg END -->

	<div class="container">
		<div class="row mb-3">
			<div class="col-lg-6">
				<!-- Title -->
				<h2 class="mb-3">Ready to work with us?</h2>
				<!-- Content -->
				<p>You couldn't have made it all this way if you weren't gonna work with us...right? Feel free to contact us if you still have more enquiries; otherwise, we may take your project request below</p>
			</div>
		</div><!-- Row END -->

		<div class="row g-2 mb-4 justify-content-between align-items-center">
			
			<div class="col-lg-10">
				<!-- Title -->
				<!-- <h2 class="mb-3">Get in touch</h2> -->
				<!-- Form START -->
				<form class="row g-3" action="homeForm.php" method="POST">
					<div class="col-md-6">
						<label for="inputName" class="form-label">Name</label>
						<input type="text" class="form-control" name="fName" id="inputName" placeholder="Enter your full name">
					</div>
					<div class="col-md-6">
						<label for="inputEmail" class="form-label">Email </label>
						<input type="email" class="form-control" name="email" id="inputEmail" placeholder="Enter your email">
					</div>

					<div class="col-md-6">
						<label for="inputPhonenumber" class="form-label">Phone number (preferrably WhatsApp)</label>
						<input type="text" class="form-control" name="phone" id="inputPhonenumber" placeholder="Enter your phone number">
					</div>
					<div class="col-md-6">
						<label for="inputSubject" class="form-label">Project type</label>
            <select class="form-control" id="inputSubject" name="project">
              <option value="">-- Select --</option>
              <option value="Logo Design">Logo Design/Branding/Visual Identity</option>
              <option value="Website Design">Website Development</option>
			  <option value="Website Design">Web Application Development</option>
              <option value="Flyer Design">Other Graphic Design</option>
              <option value="Branding/Visual Identity">UI/UX Design</option>
            </select>
					</div>

					<div class="col-12">
						<label for="exampleFormControlTextarea2" class="form-label">Project Details</label>
						<textarea class="form-control" name="message" id="exampleFormControlTextarea2" rows="6" placeholder="Briefly tell us about the project"></textarea>
					</div>          
				 
					<div class="col-12">
						<!-- Button -->
						<button type="submit" name="submit" class="btn btn-warning mb-0">Send message</button>
					</div>
				</form>
				<!-- Form END -->    
			</div>			
		</div><!-- Row END -->
	</div>
</section>
<!-- =======================
Pricing plan END -->

<!-- =======================
Client START -->
<section class="py-3">
  <?php
    include('clients.html');
  ?>
</section>
<!-- =======================
Client END -->

</main>
<!-- **************** MAIN CONTENT END **************** -->

<!-- =======================
Footer START  -->
<?php
  include('footer.html');
?>
<!-- =======================
Footer END  -->

<!-- Back to top -->
<div class="back-top"><i class="bi bi-arrow-up-short position-absolute top-50 start-50 translate-middle"></i></div>

<!-- =======================
JS libraries, plugins and custom scripts -->

<!-- JQuery -->
<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>

<!-- Animate on Scroll (AOS) -->
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

<!-- Initialize AOS -->
<script>
AOS.init();
</script>

<!-- Bootstrap JS -->
<script src="assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<!-- Vendors -->
<script src="assets/vendor/tiny-slider/tiny-slider.js"></script>
<script src="assets/vendor/purecounterjs/dist/purecounter_vanilla.js"></script>
<script src="assets/vendor/glightbox/js/glightbox.min.js"></script>

<!-- Template Functions -->
<script src="assets/js/functions.js"></script>

<!-- Swiper JS -->
    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>

    <!-- Initialize Swiper -->
    <script>
      var swiper = new Swiper(".mySwiper", {
        autoplay: {
          delay: 5000,
        },
        loop: true,
        pagination: {
          el: ".swiper-pagination",
          dynamicBullets: true,
        },
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev",
        },
        grabCursor: true,
        effect: "cube",
        cubeEffect: {
          shadow: false,
          slideShadows: true,
          shadowOffset: 10,
          shadowScale: 0.95,
        },
      });

      var secSwiper = new Swiper(".mySecSwiper", {
        autoplay: {
          delay: 5000,
        },
        grabCursor: true,
        loop: true,
        effect: 'fade',
        fadeEffect: {
          crossFade: true
        },
      });
    </script>

</body>

</html>